/* Cyber Dictionary — case studies.
   GENERATED by tools/build_cases.py from cases/*.md — do not edit by hand.
   Loaded as a plain script, like terms.js, so the page works from file://. */
window.CASES = [
 {
  "id": "stuxnet",
  "title": "Stuxnet",
  "year": "2010",
  "where": "Natanz, Iran",
  "actor": "Widely attributed to the United States and Israel; never officially claimed",
  "sector": "Nuclear enrichment, industrial control",
  "kind": "Sabotage of physical infrastructure",
  "cost": "Around 1,000 centrifuges destroyed; Iran's enrichment programme set back",
  "terms": [
   "OT / ICS",
   "SCADA",
   "Air gap",
   "Zero-day",
   "Code signing abuse",
   "Sabotage",
   "Cyber warfare",
   "Attribution",
   "Critical infrastructure"
  ],
  "sources": [
   {
    "title": "Symantec — W32.Stuxnet Dossier",
    "url": "https://docs.broadcom.com/doc/security-response-w32-stuxnet-dossier-11-en"
   },
   {
    "title": "IAEA safeguards reports on Iran, 2009–2011",
    "url": "https://www.iaea.org/newscenter/focus/iran/iaea-and-iran-iaea-reports"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "Between 2009 and 2010 centrifuges at Iran's Natanz enrichment plant began failing at an unusual rate. The plant's own monitoring said everything was normal. It was not equipment failure: software was spinning the centrifuges outside their tolerances while replaying recorded normal readings to the operators watching the screens."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "Stuxnet crossed an air gap — the plant's control network was not connected to the internet, so the malware travelled on removable media. It used four Windows zero-days, an extraordinary expenditure, and drivers signed with certificates stolen from two legitimate Taiwanese hardware companies, so Windows accepted them without complaint.",
     "It was also extremely specific. It looked for a particular Siemens controller configuration, driving a particular number of frequency converters, running in a particular frequency range. On anything else it did nothing. Having found its target it altered the rotor speeds and, critically, fed the monitoring systems the readings they expected to see."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "It was found by accident, and outside Iran. The malware spread further than intended, and in June 2010 a small Belarusian antivirus firm investigating machines that kept rebooting in Iran isolated the sample. Researchers at Symantec, Kaspersky and Langner then spent months reverse-engineering it. Langner identified the target as centrifuge control. Nobody was ever charged; attribution rests on journalism, leaks and the sheer cost of the operation."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It is the first widely accepted case of code destroying physical equipment, and it ended two comfortable assumptions: that an air gap is a boundary, and that industrial control systems are too obscure to attack. Every subsequent framework for critical infrastructure security cites it. It also set a precedent that its likely authors now live with — the techniques were studied, adapted and eventually used against Western infrastructure."
    ]
   }
  ]
 },
 {
  "id": "silk-road",
  "title": "Silk Road",
  "year": "2013",
  "where": "The Tor network",
  "actor": "Ross Ulbricht, operating as Dread Pirate Roberts",
  "sector": "Dark web marketplace",
  "kind": "Criminal marketplace and its takedown",
  "cost": "About $1.2bn in sales; a life sentence, commuted in 2025",
  "terms": [
   "Silk Road",
   "Dark web",
   "Tor",
   "Hidden service",
   "Operational security failure",
   "Blockchain analysis",
   "Cash-out",
   "Takedown",
   "Dark web archive"
  ],
  "sources": [
   {
    "title": "US Attorney, SDNY — Ross Ulbricht sentencing",
    "url": "https://www.justice.gov/usao-sdny/pr/ross-ulbricht-aka-dread-pirate-roberts-sentenced-manhattan-federal-court-life-prison"
   },
   {
    "title": "FBI complaint against Ross Ulbricht (2013)",
    "url": "https://www.justice.gov/sites/default/files/usao-sdny/legacy/2015/03/25/Ulbricht%2C%20Ross%20Complaint.pdf"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "Silk Road sold drugs at scale, on the open web, for two and a half years. It ran as a Tor hidden service, took payment in bitcoin, and worked like any marketplace: vendor ratings, escrow, dispute resolution, a customer service culture. It was seized in October 2013 and its operator was arrested in a San Francisco public library, mid-session, with the laptop open and unencrypted."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "The anonymity was real and it was layered. The site was reachable only through Tor, so neither buyers nor the server learned each other's addresses. Payment was in bitcoin, then widely and wrongly believed to be anonymous. Escrow held funds until delivery, which gave strangers a reason to trust each other.",
     "None of that failed. What failed was everything around it."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "Investigators did not break Tor. They found the earliest posts advertising the site on a public forum, made months before launch under the handle *altoid* — and one later post by the same handle giving a Gmail address containing Ulbricht's real name. Other threads tied in: a Stack Overflow question about connecting to a hidden service, edited to change the name a minute after posting. Customs intercepted forged identity documents shipped to his address. Undercover agents bought from vendors and worked upward.",
     "Bitcoin, meanwhile, turned out to be the opposite of anonymous. Every transaction was public and permanent, so once any address was tied to a person, the ledger could be walked in both directions from there."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It is the standing case study in dark web investigation, and its lesson is not technical. The anonymity system held; the person using it did not. Years of listings, vendor profiles and forum threads were seized and archived, and remain evidence — the site is gone and its contents are still searchable. Successor markets learned the operational lessons and mostly still end the same way, in a takedown or an exit scam."
    ]
   }
  ]
 },
 {
  "id": "mirai",
  "title": "Mirai",
  "year": "2016",
  "where": "Global; worst felt in the eastern United States and Liberia",
  "actor": "Three US college students, later cooperating witnesses",
  "sector": "Internet infrastructure, hosting, DNS",
  "kind": "Botnet and record-breaking denial of service",
  "cost": "Dyn outage took down much of the US consumer internet for a day",
  "terms": [
   "Botnet",
   "IoT",
   "DoS / DDoS",
   "Amplification attack",
   "Reflection attack",
   "Default credentials",
   "DNS",
   "Zombie",
   "Script kiddie"
  ],
  "sources": [
   {
    "title": "US Department of Justice — Mirai botnet guilty pleas",
    "url": "https://www.justice.gov/opa/pr/justice-department-announces-charges-and-guilty-pleas-three-computer-crime-cases-involving"
   },
   {
    "title": "Cloudflare — inside the infamous Mirai IoT botnet",
    "url": "https://blog.cloudflare.com/inside-mirai-the-infamous-iot-botnet-a-retrospective-analysis/"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "In October 2016 an attack on Dyn, a DNS provider, made Twitter, Spotify, Reddit, Netflix and much else unreachable across the United States. None of those services were attacked. Their names simply stopped resolving. The traffic came from hundreds of thousands of cameras, routers and video recorders in people's homes."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "Mirai's technique was almost insultingly simple: scan the internet, try around sixty default username and password pairs, and take whatever answers. No exploit, no vulnerability — just devices shipped with credentials the owner was never told to change, and often could not.",
     "The resulting botnet was large enough to produce floods over a terabit per second, at the time unprecedented. The source code was then published, which is why Mirai variants are still doing this."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "The scale drew immediate attention, and the operators were not careful. They advertised, argued in forums, and rented the botnet out. Investigators followed the boasting, the infrastructure and the money. The three pleaded guilty in 2017; one had written Mirai partly to gain advantage in a Minecraft server protection racket."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It put device security into law. California's SB-327 and the UK's Product Security and Telecommunications Infrastructure Act both ban universal default passwords on consumer connected devices, and both trace directly to Mirai. It also made a structural point the industry had been avoiding: the security of the internet depends on equipment whose owners have no way to patch it and no reason to care, and whose manufacturers had no obligation to either."
    ]
   }
  ]
 },
 {
  "id": "equifax",
  "title": "Equifax",
  "year": "2017",
  "where": "United States, UK, Canada",
  "actor": "Attributed by the US to four members of China's PLA",
  "sector": "Credit reporting",
  "kind": "Data breach",
  "cost": "147m people's records; about $1.4bn in settlements and remediation",
  "terms": [
   "Vulnerability management",
   "Patch",
   "N-day",
   "Exfiltration",
   "Certificate",
   "Encryption in transit",
   "Personally identifiable information",
   "Sensitive PII",
   "Breach notification",
   "Data minimisation"
  ],
  "sources": [
   {
    "title": "US House Oversight Committee — report on the Equifax data breach",
    "url": "https://oversight.house.gov/wp-content/uploads/2018/12/Equifax-Report.pdf"
   },
   {
    "title": "FTC — Equifax settlement",
    "url": "https://www.ftc.gov/enforcement/refunds/equifax-data-breach-settlement"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "Attackers took the personal records of 147 million people — names, dates of birth, national identity numbers, addresses, and for some, driving licence and card numbers. The victims were not Equifax's customers. They were the subjects of files compiled about them without their involvement, and they had no way to opt out or to take their data elsewhere."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "The entry point was a known vulnerability in Apache Struts, disclosed and patched two months earlier. The organisation had a patching process; it did not have an accurate inventory, so the instruction to patch never reached the affected server.",
     "The attackers then stayed for 76 days. Two failures kept them invisible. Internal network traffic was inspected for anomalies, but the certificate on the inspection system had expired ten months earlier, so nothing was being read. And the internal network was flat enough to reach dozens of databases from the initial foothold. When the certificate was renewed, the exfiltration became visible immediately."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "By renewing an expired certificate. The moment inspection resumed, the traffic leaving the network was obvious. That is the whole story of the detection."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It became the reference case for regulators on accountability: a chief executive resigned, Congress reported, and the settlement created a consumer fund. Its technical lessons are unglamorous and universal — you cannot patch what you have not inventoried, a lapsed monitoring certificate is a blind spot rather than a warning, and flat internal networks convert one server into everything. It also sharpened the argument for data minimisation: much of what was taken had no operational reason to still be there."
    ]
   }
  ]
 },
 {
  "id": "notpetya",
  "title": "NotPetya",
  "year": "2017",
  "where": "Ukraine, then everywhere",
  "actor": "Sandworm — Russian military intelligence, GRU Unit 74455",
  "sector": "Logistics, pharmaceuticals, food, government",
  "kind": "Destructive attack",
  "cost": "Around $10bn in global damage; roughly $300m each at Maersk and Merck",
  "terms": [
   "Sandworm",
   "Wiper",
   "Supply chain attack",
   "Compromised update",
   "Ransomware",
   "Attribution",
   "Cyber warfare",
   "Proportional response"
  ],
  "sources": [
   {
    "title": "US Department of Justice indictment of six GRU officers (2020)",
    "url": "https://www.justice.gov/opa/pr/six-russian-gru-officers-charged-connection-worldwide-deployment-destructive-malware-and"
   },
   {
    "title": "UK National Cyber Security Centre attribution statement (2018)",
    "url": "https://www.ncsc.gov.uk/news/russian-military-almost-certainly-responsible-destructive-2017-cyber-attack"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "On 27 June 2017 a piece of malware disguised as ransomware spread out of Ukraine and kept going. It reached Maersk, which moves close to a fifth of the world's container freight, and stopped it. It reached Merck, Mondelez, FedEx's European arm, and the radiation monitoring at Chernobyl. It did not stop at the border because nothing told it to.",
     "The ransom note was a lie. There was no working decryption, and money was never the point: the malware was built to destroy, and dressed as crime to muddy who had done it."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "The delivery was a supply chain attack on M.E.Doc, Ukrainian tax accounting software that almost every company doing business in the country has to run. Its update server was compromised, so the malware arrived correctly signed, through a channel every victim had deliberately trusted.",
     "Once inside a network it spread on its own using EternalBlue — a leaked NSA exploit for Windows file sharing — and, where machines were patched, by harvesting credentials from memory and using legitimate administration tools to move on. Patching alone did not save you if an unpatched neighbour had your administrator password in memory."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "Attribution took a year and did not come from the malware. Investigators had the code lineage back to earlier Sandworm tooling used against Ukraine's power grid, the choice of targets, the timing on Ukraine's Constitution Day, and the fake ransom mechanism that could never have collected. Governments then added intelligence they did not publish. The United States, United Kingdom and others attributed it to the GRU in 2018; the indictment naming six officers followed in 2020."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It ended the argument about whether a cyber attack could cause physical, global, economic damage. Insurers invoked war exclusions to refuse payment, and the litigation that followed — Merck's in particular — reshaped how cyber insurance is written. For defenders it made three points concrete: an update channel is an attack surface, a flat network turns one compromise into all of them, and recovery capability matters more than prevention. Maersk rebuilt its directory from a single surviving copy in Ghana that had been offline through a power cut."
    ]
   }
  ]
 },
 {
  "id": "wannacry",
  "title": "WannaCry",
  "year": "2017",
  "where": "150 countries; worst in the UK's National Health Service",
  "actor": "Lazarus Group — North Korea",
  "sector": "Healthcare, manufacturing, telecoms",
  "kind": "Ransomware worm",
  "cost": "Around £92m to the NHS; over 19,000 appointments cancelled",
  "terms": [
   "Ransomware",
   "Worm",
   "N-day",
   "Patch",
   "End-of-life",
   "Kill switch",
   "Critical infrastructure",
   "Attribution",
   "Vulnerability management"
  ],
  "sources": [
   {
    "title": "UK National Audit Office — investigation into WannaCry and the NHS",
    "url": "https://www.nao.org.uk/reports/investigation-wannacry-cyber-attack-and-the-nhs/"
   },
   {
    "title": "US Department of Justice — charges against a Lazarus Group programmer",
    "url": "https://www.justice.gov/opa/press-release/file/1092091/dl"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "On 12 May 2017 ransomware spread across the world in hours without anyone opening anything. It encrypted machines and demanded $300 in bitcoin. In England it hit a third of NHS trusts: ambulances diverted, operations cancelled, some hospitals reduced to paper. The ransom collected almost nothing — the payment handling was so poor that even victims who paid often could not be decrypted."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "WannaCry was a worm, not an email campaign. It spread using EternalBlue, an exploit for Windows file sharing developed by the NSA and leaked two months earlier by the Shadow Brokers. Microsoft had patched it in March, two months before the outbreak.",
     "So the vulnerability was known, the patch existed, and the attack still worked — because patching a hospital estate means scheduling downtime on equipment that is in use, some of it certified only against an operating system already out of support."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "It announced itself. The more interesting moment came the same day: a researcher analysing the sample found it querying an unregistered domain and registered it, for about ten dollars. That was the kill switch — the malware checked whether the domain resolved and stopped if it did. The global spread halted that afternoon, by accident and for the price of a domain name.",
     "Attribution to North Korea came later, from code shared with earlier Lazarus tooling, infrastructure reuse and intelligence, and was formally stated by the US and UK in December 2017."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It is the clearest available demonstration that patch management is a patient safety issue, not an IT housekeeping one. The NHS review that followed drove funded remediation and central monitoring. It also raised a question governments still have not settled: the exploit was stockpiled by a state and then lost, and the damage was done with the state's own tool."
    ]
   }
  ]
 },
 {
  "id": "dprk-it-workers",
  "title": "North Korean IT workers",
  "year": "2018-present",
  "where": "Hired remotely by companies in the US, Europe and Asia; operating from China, Russia, Laos and Cambodia",
  "actor": "Democratic People's Republic of Korea, through state-run IT organisations",
  "sector": "Technology, finance, media — anyone hiring remote engineers",
  "kind": "Employment fraud, sanctions evasion, insider access",
  "cost": "Hundreds of millions of dollars a year to the DPRK; sanctions exposure for employers",
  "terms": [
   "DPRK IT worker scheme",
   "Remote worker fraud",
   "Laptop farm",
   "Facilitator",
   "Interview fraud",
   "Identity rental",
   "Impossible travel",
   "Know your employee",
   "Insider by design",
   "Geoblocking",
   "Remote access software abuse"
  ],
  "sources": [
   {
    "title": "US Department of State, Treasury and FBI advisory on DPRK IT workers",
    "url": "https://ofac.treasury.gov/media/923126/download"
   },
   {
    "title": "US Department of Justice — laptop farm prosecutions",
    "url": "https://www.justice.gov/opa/pr/justice-department-announces-arrest-facilitator-and-seizures-laptop-farms-nation-state-it"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "Thousands of North Korean IT workers have been hired, as ordinary remote employees and contractors, by companies that believed they were hiring Americans and Europeans. They did the work. They were paid, and the pay went to a sanctioned state's weapons programmes. In many cases they also kept access, or attempted extortion after being let go.",
     "This is not a hack. Every step — the application, the interview, the onboarding, the VPN, the payroll — is a legitimate business process working exactly as designed."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "Identities are bought or stolen from real people, so background checks pass against real records. Interviews are sat by proxies, or assisted with live translation and face filters. Once hired, the company laptop is shipped to a US or European address — a *laptop farm* run by a local facilitator who plugs the machines in and installs remote access software, so the connection comes from the country the employer expects. Geoblocking sees a domestic address; the worker is in Shenyang.",
     "Pay is routed through the facilitator or through cryptocurrency. A single operative often holds several jobs at once."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "Not by security tooling, which sees a legitimate employee doing legitimate work. It is found by the mismatches around the edges: impossible travel between logins, payroll details shared across supposedly unrelated employees, addresses that recur across hires, reluctance to appear on camera, a laptop that has never once connected from the home its address claims. Amazon, KnowBe4 and others have published their own detections, all of which turn on identity and human resources data rather than on malware."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It has forced identity assurance backwards into hiring. *Know your employee* — document verification, liveness checks, right-to-work confirmation, repeated rather than done once — is now a security control, not a compliance formality. It also broke the assumption underneath insider threat programmes: the insider need not be an employee who turned. They may have been placed."
    ]
   }
  ]
 },
 {
  "id": "solarwinds",
  "title": "SolarWinds",
  "year": "2020",
  "where": "United States, then allied governments and industry",
  "actor": "APT29 / Cozy Bear — Russia's foreign intelligence service, the SVR",
  "sector": "Government, technology, consulting",
  "kind": "Supply chain espionage",
  "cost": "Around 18,000 organisations received the backdoor; roughly 100 were actively exploited",
  "terms": [
   "Supply chain attack",
   "Compromised update",
   "Code signing abuse",
   "APT",
   "Backdoor",
   "Golden SAML",
   "Dwell time",
   "Persistence",
   "Attribution",
   "SBOM"
  ],
  "sources": [
   {
    "title": "CISA — Emergency Directive 21-01",
    "url": "https://www.cisa.gov/news-events/directives/ed-21-01-mitigate-solarwinds-orion-code-compromise"
   },
   {
    "title": "Mandiant — Highly evasive attacker leverages SolarWinds supply chain",
    "url": "https://cloud.google.com/blog/topics/threat-intelligence/evasive-attacker-leverages-solarwinds-supply-chain-compromises-with-sunburst-backdoor"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "Attackers got into the build system of SolarWinds Orion, a network management product, and added a backdoor to the source before it was compiled. The result was signed by SolarWinds and shipped through its update channel to some 18,000 customers, including US federal departments. From that pool the attackers picked roughly a hundred worth pursuing and left the rest alone.",
     "The first breach happened in 2019. It was found in December 2020."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "The tradecraft was patient and quiet. The backdoor slept for up to two weeks before calling home. It checked whether it was in an analysis environment. It used domain names generated to look like ordinary Orion traffic. Where it did act, the attackers frequently forged SAML tokens with stolen signing keys — *Golden SAML* — to mint their own access to cloud services, so credentials could be reset and multi-factor enforced without dislodging them.",
     "They also took care not to reuse infrastructure between victims, which is precisely what makes indicator-based detection fail."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "Not by any government monitoring, and not by SolarWinds. FireEye, itself a victim, noticed that an employee had registered a second phone for multi-factor authentication. That single anomalous enrolment led to its own breach, then to the Orion backdoor, then to everything else. A helpdesk-level detail unravelled a two-year intelligence operation."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It made software supply chain security a policy matter. The US executive order that followed required software bills of materials and secure development attestations from federal suppliers. It also settled an argument about dwell time: fourteen months, against some of the most heavily monitored networks in the world. And it demonstrated that identity, not the network, is where a modern intrusion actually lives — forged tokens survived every credential reset aimed at them."
    ]
   }
  ]
 },
 {
  "id": "twitter-2020",
  "title": "The 2020 Twitter takeover",
  "year": "2020",
  "where": "Twitter, internally",
  "actor": "Three young people, coordinated over Discord",
  "sector": "Social media",
  "kind": "Social engineering and insider tool abuse",
  "cost": "About $118,000 in bitcoin; the accounts of presidents and corporations posting fraud",
  "terms": [
   "Social engineering",
   "Vishing",
   "Pretexting",
   "Privileged access management",
   "Insider threat",
   "Segregation of duties",
   "Account takeover",
   "Just-in-time access",
   "Least privilege"
  ],
  "sources": [
   {
    "title": "New York Department of Financial Services — investigation report",
    "url": "https://www.dfs.ny.gov/Twitter_Report"
   },
   {
    "title": "US Department of Justice — charges in the Twitter hack",
    "url": "https://www.justice.gov/usao-ndca/pr/three-individuals-charged-alleged-roles-twitter-hack"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "On 15 July 2020 the accounts of Barack Obama, Joe Biden, Elon Musk, Apple and dozens more posted the same bitcoin scam. Twitter eventually stopped every verified account on the platform from tweeting in order to end it. The attackers were teenagers, and their take was about $118,000."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "There was no malware. They phoned Twitter employees, claiming to be from the company's own IT help desk, and walked them through a credential page that captured the login and the multi-factor code in real time. That got them into internal tooling — an administration panel that could change the email address on any account, and so take it over without ever knowing its password.",
     "The panel was reachable by a large number of employees, and it did not require a second person to approve an account takeover."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "Immediately and publicly, because the attack was noisy by design. The interesting investigation was the regulator's. New York's Department of Financial Services examined why a help desk call could reach the account of a presidential candidate, and its report is unusually direct about the structural answer: too many people held too much internal capability, with too little friction on its most dangerous actions."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It reframed the risk of internal administrative tooling. The controls the report pushed toward — least privilege on support tools, just-in-time elevation, two-person approval for irreversible actions, and phishing-resistant authentication for staff — are now standard recommendations. It also made the political point unavoidable: the same panel could have been used quietly, during an election, by an actor with more patience than these three had."
    ]
   }
  ]
 },
 {
  "id": "colonial-pipeline",
  "title": "Colonial Pipeline",
  "year": "2021",
  "where": "Eastern United States",
  "actor": "DarkSide, a ransomware-as-a-service operation",
  "sector": "Energy, fuel distribution",
  "kind": "Ransomware",
  "cost": "$4.4m ransom paid, $2.3m recovered; days of fuel shortages across the US east coast",
  "terms": [
   "Ransomware",
   "Ransomware-as-a-service",
   "VPN",
   "Multi-factor authentication",
   "Credential stuffing",
   "Critical infrastructure",
   "Blockchain analysis",
   "Double extortion",
   "Business continuity"
  ],
  "sources": [
   {
    "title": "US Department of Justice — recovery of the ransom payment",
    "url": "https://www.justice.gov/opa/pr/department-justice-seizes-23-million-cryptocurrency-paid-ransomware-extortionists-darkside"
   },
   {
    "title": "CISA and FBI joint advisory on DarkSide ransomware",
    "url": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa21-131a"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "In May 2021 ransomware encrypted the business systems of the company operating the largest fuel pipeline in the United States. The pipeline's control systems were not encrypted — the company shut the pipeline down itself, because with billing systems offline it could not measure what it was delivering or bill for it. Fuel shortages and panic buying followed across the east coast, and the effect was national before any operational technology was touched."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "The way in was a single password. An old VPN account, no longer in use, still worked and had no multi-factor authentication on it. The password appeared in a batch of leaked credentials, suggesting reuse elsewhere. From there DarkSide's affiliates did the ordinary thing: moved laterally, stole data for extortion leverage, and encrypted.",
     "DarkSide itself did not run the attack. It rented the malware and the negotiation infrastructure to affiliates for a share, the model that made ransomware an industry rather than a craft."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "The company knew within hours. The interesting investigation came after: the FBI followed the bitcoin ransom across the public ledger to a specific wallet and seized most of it, having obtained the private key. That recovery did more to change ransomware economics than any advisory — it demonstrated publicly that the payment rail is the traceable part."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It moved ransomware from an IT problem to a national security one. In the United States it produced an executive order on cybersecurity, mandatory incident reporting for pipelines, and TSA security directives for the sector. The operational lesson is narrower and harder: one dormant account without MFA, and a billing system whose failure stops the physical business, were enough."
    ]
   }
  ]
 },
 {
  "id": "log4shell",
  "title": "Log4Shell",
  "year": "2021",
  "where": "Everywhere Java is deployed",
  "actor": "Everyone, within hours — from state actors to cryptominers",
  "sector": "All",
  "kind": "Vulnerability in a ubiquitous dependency",
  "cost": "Unquantifiable; years of remediation still running",
  "terms": [
   "CVE / CVSS",
   "Dependency",
   "SBOM",
   "SCA",
   "Zero-day",
   "Vulnerability management",
   "Supply chain attack",
   "Injection",
   "KEV",
   "Technical debt"
  ],
  "sources": [
   {
    "title": "CISA — Apache Log4j vulnerability guidance",
    "url": "https://www.cisa.gov/news-events/news/apache-log4j-vulnerability-guidance"
   },
   {
    "title": "Cyber Safety Review Board — review of the Log4j event",
    "url": "https://www.cisa.gov/sites/default/files/publications/CSRB-Report-on-Log4-July-11-2022_508.pdf"
   }
  ],
  "sections": [
   {
    "heading": "What happened",
    "paragraphs": [
     "In December 2021 it emerged that Log4j — a logging library present in an enormous share of Java applications — would, on being asked to log a specially crafted string, go and fetch and execute code from a server named in that string. Anything that wrote a user-supplied value to a log was exploitable, which meant almost everything.",
     "Proof of concept was trivial. Exploitation was global within hours."
    ]
   },
   {
    "heading": "How it worked",
    "paragraphs": [
     "The library supported a lookup syntax inside log messages. One of those lookups could resolve over JNDI, which could point at a remote directory, which could return a Java class that would then be loaded and run. Each of those features was reasonable in isolation and had been there for years.",
     "The severity came from where it sat: not in a product anyone had bought, but in a dependency of a dependency, maintained by a handful of unpaid volunteers, and present in software whose owners did not know they were using it."
    ]
   },
   {
    "heading": "How it was found",
    "paragraphs": [
     "Reported responsibly to Apache by a security engineer at Alibaba. What followed exposed the real problem — most organisations could not answer whether they were affected, because nothing told them what their software contained. The remediation effort was mostly an inventory exercise, and for many it took months."
    ]
   },
   {
    "heading": "What changed",
    "paragraphs": [
     "It made software bills of materials a requirement rather than an aspiration, and gave composition analysis tooling its business case. The US Cyber Safety Review Board's report concluded that Log4Shell would be exploited for a decade and framed the deeper issue: critical infrastructure resting on unfunded volunteer maintenance. Open source funding initiatives that exist today were argued for on the back of this event."
    ]
   }
  ]
 }
];
