/* Cyber Dictionary — term data.
   Loaded as a plain script (not fetch) so the page also works from file://.
   Each entry: t = term, a = abbreviation or alias, d = domain, def = plain definition. */
window.DOMAINS = [
  "Networking & Protocols",
  "Cryptography",
  "Identity & Access",
  "Attacks & Exploitation",
  "Malware & Threat Actors",
  "Application Security",
  "Cloud & Infrastructure",
  "Endpoints & Systems",
  "Defense & Operations",
  "Governance, Risk & Compliance",
  "AI & Emerging Tech",
  "Dev & Delivery"
];
window.TERMS = [
/* --- Networking & Protocols --- */
{t:"IP address",a:"Internet Protocol address",d:"Networking & Protocols",def:"The number that identifies a device on a network so traffic can be routed to it. IPv4 looks like 192.0.2.10; IPv6 is longer and hexadecimal."},
{t:"Subnet",a:"",d:"Networking & Protocols",def:"A slice of a larger network, carved out so that traffic inside it stays local and traffic leaving it has to pass a router. Written as a CIDR range like 10.0.1.0/24."},
{t:"CIDR",a:"Classless Inter-Domain Routing",d:"Networking & Protocols",def:"The /24-style notation for writing a block of IP addresses. The number after the slash says how many leading bits are fixed — the bigger the number, the smaller the block."},
{t:"NAT",a:"Network Address Translation",d:"Networking & Protocols",def:"A router rewriting private internal addresses into one public address on the way out. It is why a whole office can share a single IP, and why inbound connections need explicit port forwarding."},
{t:"Port",a:"",d:"Networking & Protocols",def:"A numbered door on a host. The IP gets you to the machine; the port gets you to the specific service — 22 for SSH, 443 for HTTPS."},
{t:"TCP",a:"Transmission Control Protocol",d:"Networking & Protocols",def:"The reliable transport: it sets up a connection, numbers every packet, and re-sends anything lost. Slower to start, but nothing arrives out of order."},
{t:"UDP",a:"User Datagram Protocol",d:"Networking & Protocols",def:"Fire-and-forget transport with no handshake and no re-sends. Used where speed beats completeness — DNS, video, games — and popular with attackers for spoofing and amplification."},
{t:"Three-way handshake",a:"SYN / SYN-ACK / ACK",d:"Networking & Protocols",def:"The three packets TCP exchanges to open a connection. Half-finished handshakes left open on purpose are the basis of the SYN flood attack."},
{t:"DNS",a:"Domain Name System",d:"Networking & Protocols",def:"The internet's phone book: it turns names like example.com into IP addresses. Almost every attack chain touches it, which is why DNS logs are gold for investigators."},
{t:"DNS resolver",a:"Recursive resolver",d:"Networking & Protocols",def:"The server that does the lookup legwork on your behalf, walking from the root servers down to the authoritative one and caching the answer."},
{t:"Authoritative name server",a:"",d:"Networking & Protocols",def:"The server that holds the real, official records for a domain. Everything else is a cached copy of what it said."},
{t:"DNSSEC",a:"DNS Security Extensions",d:"Networking & Protocols",def:"Cryptographic signatures on DNS records so a resolver can tell a genuine answer from a forged one. It proves authenticity, not confidentiality — the query is still visible."},
{t:"DoH / DoT",a:"DNS over HTTPS / DNS over TLS",d:"Networking & Protocols",def:"Encrypted DNS lookups. Good for user privacy, awkward for defenders, because it hides the query from the network monitoring that used to see it."},
{t:"DNS tunnelling",a:"",d:"Networking & Protocols",def:"Smuggling data in and out of a network inside DNS queries and responses. Slow, noisy if you look for it, and effective because DNS is rarely blocked."},
{t:"HTTP",a:"Hypertext Transfer Protocol",d:"Networking & Protocols",def:"The request-and-response protocol the web runs on. Plain HTTP is unencrypted, so anything sent over it can be read or altered in transit."},
{t:"HTTPS",a:"HTTP over TLS",d:"Networking & Protocols",def:"HTTP wrapped in TLS encryption. It proves you are talking to the site named in the certificate and stops anyone in the middle reading or editing the traffic."},
{t:"TLS",a:"Transport Layer Security",d:"Networking & Protocols",def:"The protocol that encrypts and authenticates most internet traffic. SSL is its dead predecessor — people still say SSL, but they mean TLS."},
{t:"TLS handshake",a:"",d:"Networking & Protocols",def:"The opening exchange where client and server agree a cipher, verify the certificate, and derive session keys before any real data moves."},
{t:"SNI",a:"Server Name Indication",d:"Networking & Protocols",def:"The field in a TLS handshake that names which site you want, sent before encryption starts. It leaks the hostname to anyone watching, which is what Encrypted Client Hello is meant to fix."},
{t:"mTLS",a:"Mutual TLS",d:"Networking & Protocols",def:"TLS where both sides present certificates, not just the server. Common between internal services because it authenticates the client without passwords."},
{t:"VPN",a:"Virtual Private Network",d:"Networking & Protocols",def:"An encrypted tunnel that makes a remote device behave as if it were on the internal network. It moves the trust boundary — it does not remove it."},
{t:"IPsec",a:"Internet Protocol Security",d:"Networking & Protocols",def:"A suite for encrypting and authenticating traffic at the IP layer, used for site-to-site VPNs. Works below the application, so apps need no changes."},
{t:"WireGuard",a:"",d:"Networking & Protocols",def:"A modern VPN protocol with a deliberately small codebase and a fixed set of modern ciphers. Faster and easier to audit than IPsec or OpenVPN."},
{t:"Proxy",a:"",d:"Networking & Protocols",def:"A middleman that makes requests on your behalf. A forward proxy fronts clients, a reverse proxy fronts servers, and both are natural places to inspect or filter traffic."},
{t:"Reverse proxy",a:"",d:"Networking & Protocols",def:"A server that sits in front of your applications, terminating TLS and passing requests inward. Where load balancing, caching, and web application firewalls usually live."},
{t:"Load balancer",a:"",d:"Networking & Protocols",def:"Spreads incoming traffic across several backend servers, and takes unhealthy ones out of rotation. Also a single point to enforce TLS and rate limits."},
{t:"Firewall",a:"",d:"Networking & Protocols",def:"A control that allows or blocks traffic by rule — usually address, port, and protocol. The traditional perimeter device, now also a per-host and per-cloud-resource control."},
{t:"NGFW",a:"Next-Generation Firewall",d:"Networking & Protocols",def:"A firewall that also identifies the application and user behind the traffic, not just ports and IPs, and can inspect decrypted sessions."},
{t:"IDS / IPS",a:"Intrusion Detection / Prevention System",d:"Networking & Protocols",def:"Sensors that watch traffic for known-bad patterns. An IDS alerts; an IPS sits inline and drops the traffic, which is more useful and more dangerous."},
{t:"Network segmentation",a:"",d:"Networking & Protocols",def:"Splitting a network into zones with controlled paths between them so a foothold in one zone does not reach everything. The single most effective limit on lateral movement."},
{t:"Microsegmentation",a:"",d:"Networking & Protocols",def:"Segmentation taken down to the individual workload, with policy attached to the service rather than the subnet. Usually enforced by agents or a service mesh."},
{t:"VLAN",a:"Virtual LAN",d:"Networking & Protocols",def:"A logical network laid over shared switch hardware, so two ports on the same switch can be on separate networks. A control, but a soft one — VLAN hopping is a real attack."},
{t:"ARP",a:"Address Resolution Protocol",d:"Networking & Protocols",def:"Maps IP addresses to hardware MAC addresses on a local network. It has no authentication at all, which is why ARP spoofing is trivial on a flat network."},
{t:"DHCP",a:"Dynamic Host Configuration Protocol",d:"Networking & Protocols",def:"Hands out IP addresses and network settings to devices as they join. A rogue DHCP server can quietly point every new device at an attacker's gateway and DNS."},
{t:"BGP",a:"Border Gateway Protocol",d:"Networking & Protocols",def:"How the internet's large networks tell each other which address ranges they can reach. Built on trust, so a bad or malicious announcement can hijack traffic globally."},
{t:"MAC address",a:"Media Access Control address",d:"Networking & Protocols",def:"The hardware identifier burned into a network interface. Useful for local identification, useless as an authenticator — it can be changed in one command."},
{t:"Packet capture",a:"PCAP",d:"Networking & Protocols",def:"A raw recording of network traffic, read with tools like Wireshark or tcpdump. The ground truth when logs disagree about what actually crossed the wire."},
{t:"NetFlow",a:"Flow data",d:"Networking & Protocols",def:"Summary records of who talked to whom, for how long, and how much — without the contents. Cheap to keep for a long time, which makes it the backbone of retrospective hunting."},
{t:"Air gap",a:"",d:"Networking & Protocols",def:"Physically isolating a system from other networks. Strong in principle, routinely defeated in practice by USB drives, maintenance laptops, and forgotten management links."},
/* --- Cryptography --- */
{t:"Plaintext / ciphertext",a:"",d:"Cryptography",def:"Plaintext is the readable data; ciphertext is what it looks like after encryption. Encryption turns one into the other, decryption turns it back."},
{t:"Symmetric encryption",a:"",d:"Cryptography",def:"One shared key both encrypts and decrypts. Fast, ideal for bulk data, but everyone who needs to read it needs the same secret — which is the hard part."},
{t:"Asymmetric encryption",a:"Public-key cryptography",d:"Cryptography",def:"A key pair: the public key encrypts or verifies, the private key decrypts or signs. Slower, but it lets strangers exchange secrets without meeting first."},
{t:"AES",a:"Advanced Encryption Standard",d:"Cryptography",def:"The default symmetric cipher, normally with 128- or 256-bit keys. Unbroken in practice — failures around it are nearly always key management or mode-of-operation mistakes."},
{t:"RSA",a:"Rivest–Shamir–Adleman",d:"Cryptography",def:"The classic public-key algorithm, based on the difficulty of factoring large numbers. Still common, but large and slow next to elliptic curve, and a prime target for quantum attacks."},
{t:"ECC",a:"Elliptic Curve Cryptography",d:"Cryptography",def:"Public-key cryptography over elliptic curves, giving the same strength as RSA with far smaller keys. The default for new TLS and signing work."},
{t:"Diffie–Hellman",a:"DH / ECDH",d:"Cryptography",def:"A method for two parties to agree a shared secret over a channel anyone can watch, without ever sending the secret itself."},
{t:"Forward secrecy",a:"PFS",d:"Cryptography",def:"Using fresh, throwaway keys per session so that stealing the long-term private key later does not decrypt traffic captured earlier."},
{t:"Hash function",a:"",d:"Cryptography",def:"A one-way function turning any input into a fixed-length fingerprint. Same input always gives the same digest; the digest cannot be reversed back to the input."},
{t:"SHA-256",a:"Secure Hash Algorithm 256",d:"Cryptography",def:"The workhorse hash for integrity checks, signatures, and blockchains. SHA-1 and MD5 are its broken predecessors and should never be used for security."},
{t:"Collision",a:"",d:"Cryptography",def:"Two different inputs producing the same hash. Once collisions are practical — as with MD5 and SHA-1 — the hash can no longer prove a file is unmodified."},
{t:"Salt",a:"",d:"Cryptography",def:"Random data added to a password before hashing, unique per user. It stops one precomputed table cracking every account at once."},
{t:"Pepper",a:"",d:"Cryptography",def:"A secret value mixed into password hashing and stored separately from the database, so a database dump alone is not enough to start cracking."},
{t:"Key derivation function",a:"KDF — bcrypt, scrypt, Argon2, PBKDF2",d:"Cryptography",def:"A deliberately slow, memory-hungry hash for passwords. Slowness is the feature: it makes brute-force guessing expensive."},
{t:"Rainbow table",a:"",d:"Cryptography",def:"A precomputed lookup from hashes back to passwords. Defeated entirely by per-user salting, which is why unsalted hashes are treated as plaintext."},
{t:"HMAC",a:"Hash-based Message Authentication Code",d:"Cryptography",def:"A hash keyed with a shared secret, proving both that a message is unaltered and that it came from someone holding the key."},
{t:"Digital signature",a:"",d:"Cryptography",def:"A hash of a message encrypted with the sender's private key. Anyone with the public key can confirm authorship and that nothing changed — and the signer cannot credibly deny it."},
{t:"Certificate",a:"X.509 certificate",d:"Cryptography",def:"A signed statement binding a public key to an identity such as a domain name. Trust rests entirely on trusting whoever signed it."},
{t:"Certificate authority",a:"CA",d:"Cryptography",def:"An organisation that issues and vouches for certificates. Its root certificate ships in browsers and operating systems, so a compromised CA breaks trust everywhere."},
{t:"PKI",a:"Public Key Infrastructure",d:"Cryptography",def:"The whole apparatus of issuing, distributing, renewing, and revoking certificates and keys. Most PKI incidents are expiries and misissuance, not cryptographic breaks."},
{t:"Certificate pinning",a:"",d:"Cryptography",def:"Hard-coding which certificate or key an app will accept, so a rogue CA cannot impersonate the server. Powerful, and easy to brick your own app with."},
{t:"CRL / OCSP",a:"Certificate Revocation List / Online Certificate Status Protocol",d:"Cryptography",def:"The two ways to check whether a certificate has been revoked early. Both are patchy in practice, which is why short-lived certificates are now preferred."},
{t:"Let's Encrypt / ACME",a:"Automatic Certificate Management Environment",d:"Cryptography",def:"A free CA and the protocol that automates issuing and renewing certificates. It made HTTPS the default rather than an upgrade."},
{t:"Encryption at rest",a:"",d:"Cryptography",def:"Data encrypted while stored on disk, so stolen hardware or a copied volume is useless. It does not protect data while the system is running and the key is loaded."},
{t:"Encryption in transit",a:"",d:"Cryptography",def:"Data encrypted while moving over a network. The pair to encryption at rest — most compliance regimes ask for both."},
{t:"End-to-end encryption",a:"E2EE",d:"Cryptography",def:"Only the sender and recipient hold the keys; the service carrying the message cannot read it. The distinction that matters when a provider is subpoenaed or breached."},
{t:"Key management",a:"KMS",d:"Cryptography",def:"Generating, storing, rotating, and retiring keys. Almost every real-world crypto failure is a key management failure, not a broken algorithm."},
{t:"HSM",a:"Hardware Security Module",d:"Cryptography",def:"A tamper-resistant device that generates and uses keys without ever exporting them. The key can be used but not copied, even by an administrator."},
{t:"TPM",a:"Trusted Platform Module",d:"Cryptography",def:"A small secure chip on a motherboard that stores keys and measures boot integrity. What full-disk encryption and secure boot lean on."},
{t:"Nonce / IV",a:"Number used once / Initialisation Vector",d:"Cryptography",def:"A unique value per encryption operation so identical plaintexts do not produce identical ciphertexts. Reusing one can collapse the security of the whole scheme."},
{t:"Entropy",a:"",d:"Cryptography",def:"Genuine unpredictability. Keys and tokens generated from weak entropy are guessable no matter how strong the algorithm."},
{t:"CSPRNG",a:"Cryptographically Secure Pseudo-Random Number Generator",d:"Cryptography",def:"A random source safe for keys and tokens. Ordinary language random() functions are not, and using one for a session token is a classic bug."},
{t:"Side-channel attack",a:"",d:"Cryptography",def:"Recovering secrets from physical or timing leakage rather than breaking the maths — power draw, execution time, cache behaviour, even sound."},
{t:"Constant-time comparison",a:"",d:"Cryptography",def:"Comparing secrets in a way that always takes the same time, so an attacker cannot learn the value one character at a time from response timing."},
{t:"Post-quantum cryptography",a:"PQC",d:"Cryptography",def:"Algorithms designed to survive quantum computers, now standardised as ML-KEM and ML-DSA. Being adopted early because encrypted traffic stolen today could be decrypted later."},
{t:"Harvest now, decrypt later",a:"",d:"Cryptography",def:"Recording encrypted traffic today in the expectation of breaking it with future technology. The reason long-lived secrets need post-quantum protection now, not eventually."},
{t:"Homomorphic encryption",a:"",d:"Cryptography",def:"Computing directly on encrypted data without decrypting it. Real, but still slow enough that it is used narrowly rather than by default."},
{t:"Steganography",a:"",d:"Cryptography",def:"Hiding a message inside something innocuous, such as an image, so nobody knows a message exists. Concealment rather than encryption — often used to smuggle payloads past filters."},
/* --- Identity & Access --- */
{t:"Authentication",a:"AuthN",d:"Identity & Access",def:"Proving who you are. Distinct from authorisation, and confusing the two is the root of a surprising number of vulnerabilities."},
{t:"Authorisation",a:"AuthZ",d:"Identity & Access",def:"Deciding what an already-identified user is allowed to do. A logged-in user reaching another user's record is an authorisation failure, not an authentication one."},
{t:"Multi-factor authentication",a:"MFA / 2FA",d:"Identity & Access",def:"Requiring two or more different kinds of proof — something you know, have, or are. The single highest-value control against stolen passwords."},
{t:"TOTP",a:"Time-based One-Time Password",d:"Identity & Access",def:"The rotating six-digit code from an authenticator app. Far better than SMS, but still phishable, because the user can be tricked into typing it into a fake site."},
{t:"Phishing-resistant MFA",a:"",d:"Identity & Access",def:"Factors bound to the real domain so they cannot be relayed to a fake one — hardware security keys and passkeys. Codes and push prompts are not phishing-resistant."},
{t:"FIDO2 / WebAuthn",a:"",d:"Identity & Access",def:"The open standards behind hardware keys and passkeys. The browser signs a challenge with a key tied to the exact origin, so a lookalike site gets nothing."},
{t:"Passkey",a:"",d:"Identity & Access",def:"A WebAuthn credential stored on a device or synced through a platform account, replacing the password entirely. Unlocked with a fingerprint, face, or PIN."},
{t:"Security key",a:"Hardware token, YubiKey",d:"Identity & Access",def:"A physical device that holds authentication keys and requires a touch to use. The strongest widely-available second factor."},
{t:"SSO",a:"Single Sign-On",d:"Identity & Access",def:"One login granting access to many applications. It centralises control and logging — and centralises risk, since the identity provider becomes the crown jewel."},
{t:"IdP",a:"Identity Provider",d:"Identity & Access",def:"The system that authenticates users and vouches for them to applications — Entra ID, Okta, Google Workspace. Compromise it and every downstream app follows."},
{t:"SAML",a:"Security Assertion Markup Language",d:"Identity & Access",def:"The older XML-based standard for federated SSO, still standard in enterprise software. Its signature handling has a long history of bypass bugs."},
{t:"OAuth 2.0",a:"",d:"Identity & Access",def:"A delegation framework: it lets an app act on your behalf against another service without ever seeing your password. It is about access, not identity."},
{t:"OIDC",a:"OpenID Connect",d:"Identity & Access",def:"An identity layer built on top of OAuth 2.0. OAuth grants access; OIDC actually tells the app who you are, in a signed ID token."},
{t:"JWT",a:"JSON Web Token",d:"Identity & Access",def:"A signed, self-describing token carrying claims about a user. Readable by anyone holding it — signed, not secret — so never put anything confidential inside."},
{t:"Bearer token",a:"",d:"Identity & Access",def:"A credential where possession alone grants access, with no further proof required. Which is exactly why leaked tokens in logs or repos are so damaging."},
{t:"Session hijacking",a:"",d:"Identity & Access",def:"Stealing a valid session cookie or token to become an already-authenticated user, skipping login and MFA entirely. Infostealer malware's main product."},
{t:"Token binding / DPoP",a:"",d:"Identity & Access",def:"Tying a token to the client that requested it, so a stolen token is useless elsewhere. The countermeasure to plain bearer tokens."},
{t:"RBAC",a:"Role-Based Access Control",d:"Identity & Access",def:"Permissions attached to roles, and roles attached to people. Simple and auditable, until the roles multiply and everyone ends up in several."},
{t:"ABAC",a:"Attribute-Based Access Control",d:"Identity & Access",def:"Access decided by attributes — department, device posture, location, time — evaluated as policy. More expressive than roles, and harder to reason about."},
{t:"Least privilege",a:"",d:"Identity & Access",def:"Give each account only the access its job requires, and no more. The principle nearly every access review is trying to enforce."},
{t:"Privilege escalation",a:"",d:"Identity & Access",def:"Gaining rights beyond those granted. Vertical means user to admin; horizontal means reaching another user's data at the same level."},
{t:"PAM",a:"Privileged Access Management",d:"Identity & Access",def:"Controls specifically for admin accounts — vaulted credentials, checkout with approval, session recording, and automatic rotation."},
{t:"Just-in-time access",a:"JIT",d:"Identity & Access",def:"Granting elevated rights only for a defined window, then removing them automatically. Replaces standing admin access, which is what attackers actually hunt for."},
{t:"Service account",a:"Machine identity",d:"Identity & Access",def:"A non-human account used by an application or script. Typically over-permissioned, rarely rotated, never MFA-protected — a standing favourite for attackers."},
{t:"Workload identity",a:"",d:"Identity & Access",def:"Giving a running service a short-lived, automatically issued identity instead of a static key. The modern replacement for hard-coded credentials."},
{t:"Federation",a:"",d:"Identity & Access",def:"Trusting another organisation's identity provider so their users can access your systems without separate accounts. Convenient, and it exports your trust decision."},
{t:"Directory service",a:"Active Directory, LDAP",d:"Identity & Access",def:"The central store of users, groups, and computers. In most enterprises, compromising Active Directory is functionally the same as compromising everything."},
{t:"Kerberos",a:"",d:"Identity & Access",def:"The ticket-based authentication protocol underneath Windows domains. Its ticket mechanics give rise to Kerberoasting, Golden Ticket, and Silver Ticket attacks."},
{t:"Pass-the-hash",a:"PtH",d:"Identity & Access",def:"Authenticating with a stolen password hash without ever cracking it, because the protocol accepts the hash as proof."},
{t:"Kerberoasting",a:"",d:"Identity & Access",def:"Requesting service tickets for accounts with weak passwords and cracking them offline. Quiet, effective, and needs only an ordinary domain account to start."},
{t:"Golden Ticket",a:"",d:"Identity & Access",def:"Forging Kerberos tickets using the domain's krbtgt key, granting an attacker persistent, self-issued access to anything in the domain."},
{t:"Credential stuffing",a:"",d:"Identity & Access",def:"Replaying username and password pairs from earlier breaches against other sites, betting on reuse. Cheap, automated, and depressingly effective."},
{t:"Password spraying",a:"",d:"Identity & Access",def:"Trying one or two common passwords across many accounts, staying under lockout thresholds. Slower than brute force and far less likely to trip alarms."},
{t:"Account takeover",a:"ATO",d:"Identity & Access",def:"An attacker gaining full control of a legitimate account, then using its normal permissions. Hard to spot precisely because nothing technically breaks."},
{t:"Identity lifecycle",a:"Joiner–Mover–Leaver",d:"Identity & Access",def:"Provisioning access on hire, adjusting it on transfer, and removing it on exit. Leaver failures — dormant accounts with live access — are a recurring audit finding."},
{t:"SCIM",a:"System for Cross-domain Identity Management",d:"Identity & Access",def:"The standard for pushing user creation, updates, and deprovisioning from an identity provider into applications automatically."},
{t:"Access review",a:"Recertification / attestation",d:"Identity & Access",def:"A periodic check where owners confirm who still needs access. The main defence against privilege creep — and often rubber-stamped."},
{t:"Zero trust",a:"",d:"Identity & Access",def:"Assume no network location is trusted; verify identity, device, and context on every request. A design principle, not a product, whatever a vendor tells you."},
/* --- Attacks & Exploitation --- */
{t:"Threat / vulnerability / risk",a:"",d:"Attacks & Exploitation",def:"A threat is who might hurt you, a vulnerability is the weakness they would use, and risk is the combination weighted by likelihood and impact. Vendors blur these constantly."},
{t:"Attack surface",a:"",d:"Attacks & Exploitation",def:"Everything an attacker could touch — exposed services, endpoints, APIs, staff, suppliers. Reducing it is usually cheaper than defending it."},
{t:"Exploit",a:"",d:"Attacks & Exploitation",def:"Working code or a technique that turns a vulnerability into actual unauthorised behaviour. A vulnerability is theoretical until an exploit exists."},
{t:"Payload",a:"",d:"Attacks & Exploitation",def:"The part of an attack that does the intended damage or gives access, as opposed to the delivery mechanism that gets it there."},
{t:"Zero-day",a:"0-day",d:"Attacks & Exploitation",def:"A vulnerability being exploited before a patch exists. Rare and expensive — most breaches still use flaws patched months earlier."},
{t:"N-day",a:"One-day",d:"Attacks & Exploitation",def:"A known, patched vulnerability that is still exploitable because the target has not applied the fix. The overwhelming majority of real intrusions."},
{t:"Proof of concept",a:"PoC",d:"Attacks & Exploitation",def:"Minimal code demonstrating that a vulnerability is genuinely exploitable. Public PoC release usually marks the start of mass scanning."},
{t:"Phishing",a:"",d:"Attacks & Exploitation",def:"A fraudulent message designed to make someone hand over credentials or run something. Still the most common way intrusions begin."},
{t:"Spear phishing",a:"",d:"Attacks & Exploitation",def:"Phishing tailored to one person using real details about their role, colleagues, or current projects. Much higher success rate, much lower volume."},
{t:"Whaling",a:"",d:"Attacks & Exploitation",def:"Spear phishing aimed at executives, whose approval authority and access make a single success unusually valuable."},
{t:"BEC",a:"Business Email Compromise",d:"Attacks & Exploitation",def:"Impersonating or hijacking a trusted business mailbox to redirect a payment or an invoice. Consistently causes larger financial losses than ransomware."},
{t:"Smishing / vishing",a:"",d:"Attacks & Exploitation",def:"Phishing by SMS and by voice call. Voice versions increasingly use cloned audio, and helpdesk vishing is a proven route past MFA."},
{t:"Social engineering",a:"",d:"Attacks & Exploitation",def:"Manipulating people rather than systems — urgency, authority, helpfulness. It bypasses technical controls by using someone who already holds legitimate access."},
{t:"Pretexting",a:"",d:"Attacks & Exploitation",def:"Inventing a plausible scenario and identity to justify an unusual request. The setup that makes the eventual ask feel routine."},
{t:"MFA fatigue",a:"Push bombing",d:"Attacks & Exploitation",def:"Spamming approval prompts until a tired user taps accept. Countered with number matching or by dropping push approval altogether."},
{t:"Adversary-in-the-middle",a:"AiTM / MitM",d:"Attacks & Exploitation",def:"Sitting between the user and the real site, relaying traffic and capturing the session cookie after login. It defeats codes and push, but not hardware-bound factors."},
{t:"SIM swapping",a:"",d:"Attacks & Exploitation",def:"Convincing a mobile carrier to move a number to an attacker's SIM, capturing every SMS code. The reason SMS is the weakest second factor."},
{t:"Watering hole",a:"",d:"Attacks & Exploitation",def:"Compromising a site the intended victims already visit and waiting for them to arrive. No message to the target means nothing to flag as suspicious."},
{t:"Drive-by download",a:"",d:"Attacks & Exploitation",def:"Malware installed simply by loading a page, exploiting the browser or a plugin without any click."},
{t:"Malvertising",a:"",d:"Attacks & Exploitation",def:"Malicious code delivered through legitimate ad networks, so a trusted site serves it unknowingly."},
{t:"Typosquatting",a:"",d:"Attacks & Exploitation",def:"Registering near-miss domains or package names to catch typos. Used both for phishing and for poisoning software dependencies."},
{t:"Brute force",a:"",d:"Attacks & Exploitation",def:"Trying every possibility until something works. Defeated by rate limiting, lockouts, and enough entropy to make the search space impractical."},
{t:"DoS / DDoS",a:"(Distributed) Denial of Service",d:"Attacks & Exploitation",def:"Overwhelming a service so real users cannot reach it. Distributed versions use many hosts at once, often a botnet or reflected traffic."},
{t:"Amplification attack",a:"Reflection",d:"Attacks & Exploitation",def:"Sending small spoofed requests to services that reply with much larger responses, aimed at the victim. DNS and NTP are classic amplifiers."},
{t:"Botnet",a:"",d:"Attacks & Exploitation",def:"A fleet of compromised machines under one controller, rented out for denial of service, spam, proxying, or credential stuffing."},
{t:"Command and control",a:"C2 / C&C",d:"Attacks & Exploitation",def:"The channel an attacker uses to issue instructions to compromised hosts. Increasingly hidden inside normal cloud and messaging traffic."},
{t:"Beaconing",a:"",d:"Attacks & Exploitation",def:"An implant checking in with its controller at regular intervals. The rhythm of those check-ins is one of the most reliable detections available."},
{t:"Lateral movement",a:"",d:"Attacks & Exploitation",def:"Moving from the first compromised host to more valuable ones inside the network. Usually done with stolen valid credentials, not new exploits."},
{t:"Persistence",a:"",d:"Attacks & Exploitation",def:"Making access survive reboots, password resets, and cleanup — scheduled tasks, services, registry keys, rogue OAuth grants, extra SSH keys."},
{t:"Exfiltration",a:"",d:"Attacks & Exploitation",def:"Getting stolen data out, often in small encrypted chunks over allowed channels like HTTPS or a sanctioned file-sharing service."},
{t:"Living off the land",a:"LOLBins",d:"Attacks & Exploitation",def:"Using tools already installed — PowerShell, certutil, curl, WMI — instead of dropping malware. Nothing to detect as a bad file, so behaviour is the only signal."},
{t:"Fileless attack",a:"",d:"Attacks & Exploitation",def:"Malicious activity running in memory or scripting engines without writing to disk. Invisible to file-scanning antivirus by design."},
{t:"Supply chain attack",a:"",d:"Attacks & Exploitation",def:"Compromising a supplier, library, or update channel to reach everyone downstream. One breach, many victims — SolarWinds and XZ Utils are the canonical cases."},
{t:"Dependency confusion",a:"",d:"Attacks & Exploitation",def:"Publishing a public package with the same name as a company's internal one so build tools fetch the attacker's version by mistake."},
{t:"Insider threat",a:"",d:"Attacks & Exploitation",def:"Harm caused by someone with legitimate access — malicious, negligent, or coerced. Technical controls help least here; process and monitoring matter most."},
{t:"Shadow IT",a:"",d:"Attacks & Exploitation",def:"Tools and accounts staff adopt without approval. Not hostile, but invisible to security, unpatched, and outside the incident response plan."},
{t:"Initial access broker",a:"IAB",d:"Attacks & Exploitation",def:"A criminal specialising in breaking in and selling that foothold on. The reason ransomware crews can skip the intrusion step entirely."},
{t:"Attack chain",a:"Kill chain",d:"Attacks & Exploitation",def:"The ordered stages of an intrusion, from reconnaissance through to impact. Useful because breaking any single link stops the whole chain."},
/* --- Malware & Threat Actors --- */
{t:"Malware",a:"",d:"Malware & Threat Actors",def:"Any software written to do harm or gain unauthorised access. An umbrella term covering everything below it."},
{t:"Virus",a:"",d:"Malware & Threat Actors",def:"Malicious code that attaches itself to a file or program and spreads when that host is run. Largely historical, but the word stuck to everything."},
{t:"Worm",a:"",d:"Malware & Threat Actors",def:"Malware that spreads by itself across a network with no user action. Why unpatched internet-facing services are treated as emergencies."},
{t:"Trojan",a:"",d:"Malware & Threat Actors",def:"Malware disguised as something wanted — a cracked app, an installer, a document viewer. It relies on the user choosing to run it."},
{t:"Ransomware",a:"",d:"Malware & Threat Actors",def:"Malware that encrypts data and demands payment for the key. Modern operations steal the data first, so paying does not undo the breach."},
{t:"Double extortion",a:"",d:"Malware & Threat Actors",def:"Encrypting data and also threatening to publish it. Backups solve the outage but not the leak, which is why they are no longer a complete answer."},
{t:"Ransomware-as-a-service",a:"RaaS",d:"Malware & Threat Actors",def:"A criminal business model where developers rent their malware and infrastructure to affiliates for a cut. It industrialised ransomware."},
{t:"Wiper",a:"",d:"Malware & Threat Actors",def:"Malware built purely to destroy data, sometimes disguised as ransomware. There is no key, because recovery was never the point."},
{t:"Spyware",a:"",d:"Malware & Threat Actors",def:"Software that covertly monitors activity — messages, location, microphone, camera. Includes commercial surveillance tools sold to states."},
{t:"Stalkerware",a:"",d:"Malware & Threat Actors",def:"Consumer spyware marketed for monitoring partners, children, or staff. Legally grey, technically ordinary, and a serious safety issue in domestic abuse."},
{t:"Keylogger",a:"",d:"Malware & Threat Actors",def:"Records keystrokes to capture passwords and messages. Exists as software and as small hardware devices inline with a keyboard."},
{t:"Infostealer",a:"Stealer",d:"Malware & Threat Actors",def:"Malware that grabs saved passwords, cookies, and session tokens, then leaves. Its output feeds credential markets and skips MFA via stolen sessions."},
{t:"Rootkit",a:"",d:"Malware & Threat Actors",def:"Malware that hides itself deep in the operating system or below it, altering what the system reports about itself. Often only detectable from outside the host."},
{t:"Bootkit",a:"",d:"Malware & Threat Actors",def:"A rootkit that loads before the operating system, surviving reinstalls. Secure Boot and measured boot exist mainly to stop this."},
{t:"Backdoor",a:"",d:"Malware & Threat Actors",def:"A hidden way back into a system that bypasses normal authentication. Left by attackers, and occasionally by developers who meant it as a debug feature."},
{t:"RAT",a:"Remote Access Trojan",d:"Malware & Threat Actors",def:"Malware giving an attacker interactive control of a machine — files, screen, camera, shell — as if sitting at it."},
{t:"Loader / dropper",a:"",d:"Malware & Threat Actors",def:"Small first-stage malware whose only job is to fetch and run the real payload. Kept simple so it stays undetected."},
{t:"Cryptominer",a:"Cryptojacking",d:"Malware & Threat Actors",def:"Malware that quietly uses your compute to mine cryptocurrency. Low drama, but it signals that something else could have run instead."},
{t:"Adware",a:"",d:"Malware & Threat Actors",def:"Software that injects ads or hijacks searches. Mostly a nuisance, sometimes a delivery route for worse."},
{t:"Scareware",a:"",d:"Malware & Threat Actors",def:"Fake alerts claiming infection to push a purchase or a phone call. The on-ramp to tech-support fraud."},
{t:"Packer / crypter",a:"",d:"Malware & Threat Actors",def:"Tools that compress or encrypt malware so its file signature changes. Cheap evasion, which is why signature-only detection fails."},
{t:"Polymorphic malware",a:"",d:"Malware & Threat Actors",def:"Malware that rewrites its own code each time it spreads, so no two copies look alike to a scanner."},
{t:"Obfuscation",a:"",d:"Malware & Threat Actors",def:"Deliberately making code hard to read or analyse. Used by malware authors and, legitimately, by software vendors protecting their products."},
{t:"Sandbox evasion",a:"",d:"Malware & Threat Actors",def:"Malware checking whether it is being watched — virtual machine artefacts, no mouse movement, too little uptime — and staying dormant if so."},
{t:"Logic bomb",a:"",d:"Malware & Threat Actors",def:"Malicious code that triggers on a condition, such as a date or a name disappearing from payroll. Usually an insider's tool."},
{t:"Threat actor",a:"",d:"Malware & Threat Actors",def:"The person or group behind an attack. Grouped by capability and motive rather than by the tools they happen to use."},
{t:"APT",a:"Advanced Persistent Threat",d:"Malware & Threat Actors",def:"A well-resourced group, usually state-linked, that gets in and stays quietly for a long time. Persistence and patience matter more than sophistication."},
{t:"Hacktivist",a:"",d:"Malware & Threat Actors",def:"An attacker motivated by a political or social cause rather than money. Typically defacement, leaks, or denial of service."},
{t:"Script kiddie",a:"",d:"Malware & Threat Actors",def:"Someone using others' tools without understanding them. Still capable of real damage against anything left unpatched."},
{t:"Red team / blue team",a:"",d:"Malware & Threat Actors",def:"Red attacks to test defences, blue defends and detects. Purple team is the practice of running both together so findings actually improve detection."},
{t:"Threat intelligence",a:"CTI",d:"Malware & Threat Actors",def:"Analysed information about who is attacking, how, and what to look for. Useful only when it changes a decision, not when it is a feed nobody reads."},
{t:"IOC",a:"Indicator of Compromise",d:"Malware & Threat Actors",def:"An observable sign of intrusion — a hash, a domain, an IP. Easy to share, easy for attackers to change, so it dates quickly."},
{t:"TTPs",a:"Tactics, Techniques, and Procedures",d:"Malware & Threat Actors",def:"How a group operates rather than what they used once. Far more durable than indicators, and the basis of ATT&CK-style detection."},
{t:"Pyramid of Pain",a:"",d:"Malware & Threat Actors",def:"A model ranking indicators by how much it costs an attacker when you block them. Hashes are trivial to change; behaviours are not."},
{t:"MITRE ATT&CK",a:"",d:"Malware & Threat Actors",def:"A public catalogue of real-world attacker techniques, organised by tactic. The common vocabulary for describing and mapping detection coverage."},
{t:"Attribution",a:"",d:"Malware & Threat Actors",def:"Assigning an attack to a specific actor. Genuinely hard, often political, and rarely changes what a defender should do next."},
{t:"Malware family",a:"",d:"Malware & Threat Actors",def:"A cluster of related samples sharing code and behaviour. Naming is inconsistent across vendors, which is why the same thing has five names."},
{t:"Dwell time",a:"",d:"Malware & Threat Actors",def:"How long an intruder is inside before being detected. The metric that best reflects whether detection actually works."},
/* --- Application Security --- */
{t:"OWASP",a:"Open Worldwide Application Security Project",d:"Application Security",def:"A nonprofit producing free application security guidance, tools, and the widely-cited Top 10 lists."},
{t:"OWASP Top 10",a:"",d:"Application Security",def:"A periodically-updated list of the most critical web application risks. An awareness document, not a checklist to certify against."},
{t:"Injection",a:"",d:"Application Security",def:"Untrusted input being interpreted as code or commands. The root cause behind SQL injection, command injection, and most template attacks."},
{t:"SQL injection",a:"SQLi",d:"Application Security",def:"Slipping SQL into input so the database runs it. Fixed properly by parameterised queries — never by filtering quotes."},
{t:"XSS",a:"Cross-Site Scripting",d:"Application Security",def:"Injecting JavaScript that runs in another user's browser under your site's origin, letting an attacker read cookies or act as that user."},
{t:"Stored vs reflected XSS",a:"",d:"Application Security",def:"Stored XSS is saved server-side and hits every viewer; reflected XSS is echoed back from a crafted link and hits whoever clicks it."},
{t:"DOM-based XSS",a:"",d:"Application Security",def:"XSS caused entirely by client-side JavaScript writing untrusted data into the page. The server may never see the payload at all."},
{t:"CSRF",a:"Cross-Site Request Forgery",d:"Application Security",def:"Tricking a logged-in browser into sending a state-changing request the user never intended. Blocked with anti-CSRF tokens and SameSite cookies."},
{t:"SSRF",a:"Server-Side Request Forgery",d:"Application Security",def:"Making the server fetch a URL of the attacker's choosing, often reaching internal services or cloud metadata endpoints the internet cannot."},
{t:"IDOR",a:"Insecure Direct Object Reference",d:"Application Security",def:"Changing an identifier in a URL or request and getting someone else's data because the server never checked ownership."},
{t:"Broken access control",a:"",d:"Application Security",def:"Authorisation not enforced consistently on the server. Persistently the number one web risk, because it cannot be found by scanners alone."},
{t:"Path traversal",a:"Directory traversal",d:"Application Security",def:"Using ../ sequences to read files outside the intended directory, such as configuration or key material."},
{t:"Command injection",a:"",d:"Application Security",def:"User input reaching a shell command, letting an attacker run arbitrary system commands as the application's user."},
{t:"Deserialisation vulnerability",a:"",d:"Application Security",def:"Rebuilding objects from untrusted serialised data, which in many languages can trigger code execution during reconstruction."},
{t:"XXE",a:"XML External Entity",d:"Application Security",def:"Abusing XML parsers that resolve external references, allowing file reads or server-side requests. Fixed by disabling external entities."},
{t:"Race condition",a:"TOCTOU",d:"Application Security",def:"A bug where the outcome depends on timing between a check and its use. Exploited by firing simultaneous requests — a common cause of duplicate refunds and coupon abuse."},
{t:"Buffer overflow",a:"",d:"Application Security",def:"Writing past the end of a memory buffer, corrupting adjacent data and often enabling code execution. Mostly a C and C++ problem."},
{t:"Use-after-free",a:"",d:"Application Security",def:"Using memory after it has been released, letting an attacker control what now sits there. A leading source of browser and kernel exploits."},
{t:"Memory safety",a:"",d:"Application Security",def:"Preventing whole classes of memory bugs by design. The main argument for Rust, Go, and similar languages in new systems code."},
{t:"Input validation",a:"",d:"Application Security",def:"Checking that input matches an expected shape before use. Allow-lists work; deny-lists of bad characters eventually fail."},
{t:"Output encoding",a:"",d:"Application Security",def:"Escaping data for the context it lands in — HTML, attribute, JavaScript, SQL. The correct fix for XSS, applied at the point of output."},
{t:"Parameterised query",a:"Prepared statement",d:"Application Security",def:"Sending SQL structure and data separately so input can never become code. The definitive SQL injection fix."},
{t:"CSP",a:"Content Security Policy",d:"Application Security",def:"A header telling the browser which sources of script, style, and frames are allowed. A strong second line of defence when XSS slips through."},
{t:"CORS",a:"Cross-Origin Resource Sharing",d:"Application Security",def:"Rules for when one origin may read another's responses. Loosening it to a wildcard with credentials is a routine and serious misconfiguration."},
{t:"Same-origin policy",a:"SOP",d:"Application Security",def:"The browser rule that keeps one site's scripts from reading another site's data. The foundation everything else in web security sits on."},
{t:"Secure cookie flags",a:"HttpOnly, Secure, SameSite",d:"Application Security",def:"HttpOnly hides a cookie from JavaScript, Secure restricts it to HTTPS, and SameSite limits cross-site sending. Three flags, most cookie attacks covered."},
{t:"HSTS",a:"HTTP Strict Transport Security",d:"Application Security",def:"A header telling browsers to only ever use HTTPS for a domain, removing the downgrade window on first navigation."},
{t:"Subresource integrity",a:"SRI",d:"Application Security",def:"A hash on a third-party script tag so the browser refuses it if the file changed. Cheap protection against a compromised CDN."},
{t:"SAST",a:"Static Application Security Testing",d:"Application Security",def:"Scanning source code for vulnerable patterns without running it. Broad coverage, high false-positive rate."},
{t:"DAST",a:"Dynamic Application Security Testing",d:"Application Security",def:"Testing a running application from the outside. Fewer false positives, but it only finds what it can reach."},
{t:"SCA",a:"Software Composition Analysis",d:"Application Security",def:"Inventorying third-party dependencies and flagging known-vulnerable versions. Most of a modern codebase is not written in-house."},
{t:"Fuzzing",a:"",d:"Application Security",def:"Throwing malformed and random input at a program to find crashes. Extremely effective at finding memory-safety and parser bugs."},
{t:"Penetration test",a:"Pentest",d:"Application Security",def:"An authorised, time-boxed attempt to break in and prove impact. Deeper than a scan, narrower than a red team engagement."},
{t:"Bug bounty",a:"",d:"Application Security",def:"Paying external researchers for valid vulnerability reports. Continuous and broad, but no substitute for internal testing."},
{t:"Responsible disclosure",a:"Coordinated disclosure",d:"Application Security",def:"Reporting a flaw privately and agreeing a window before publication, so a fix exists before the details do."},
{t:"Secure SDLC",a:"",d:"Application Security",def:"Building security into every stage of development rather than testing at the end. Threat modelling, review, testing, and monitoring as normal practice."},
{t:"Threat modelling",a:"STRIDE",d:"Application Security",def:"Working out systematically what could go wrong with a design before it is built. Cheapest security work there is, and the most often skipped."},
{t:"Shift left",a:"",d:"Application Security",def:"Moving security checks earlier into design and development. Genuinely valuable, and frequently reduced to adding a scanner to the build."},
{t:"Secrets management",a:"",d:"Application Security",def:"Keeping credentials out of code and configuration and in a vault with rotation and audit. Hard-coded secrets in repositories remain a top breach cause."},
{t:"Hard-coded credentials",a:"",d:"Application Security",def:"Passwords or keys written directly into source. They spread through forks, logs, and backups, and cannot be rotated without a code change."},
/* --- Cloud & Infrastructure --- */
{t:"IaaS / PaaS / SaaS",a:"",d:"Cloud & Infrastructure",def:"Three levels of cloud service — raw machines, a managed platform, or finished software. The level decides how much security is yours and how much is the provider's."},
{t:"Shared responsibility model",a:"",d:"Cloud & Infrastructure",def:"The provider secures the cloud; you secure what you put in it. Nearly every cloud breach lands on the customer's side of that line."},
{t:"Public / private / hybrid cloud",a:"",d:"Cloud & Infrastructure",def:"Shared provider infrastructure, dedicated infrastructure, or a mix. Hybrid is the common reality, and the seams between the two are where control gaps live."},
{t:"Multi-cloud",a:"",d:"Cloud & Infrastructure",def:"Using more than one cloud provider. Reduces lock-in, multiplies the number of identity and policy models you must get right."},
{t:"Region / availability zone",a:"",d:"Cloud & Infrastructure",def:"A geographic location and an isolated datacentre within it. Regions matter for data residency law; zones matter for surviving hardware failure."},
{t:"Virtual machine",a:"VM",d:"Cloud & Infrastructure",def:"A simulated computer running on shared hardware, with its own operating system. Strong isolation, heavier than a container."},
{t:"Hypervisor",a:"",d:"Cloud & Infrastructure",def:"The layer that runs and isolates virtual machines. Escaping it is the most valuable cloud vulnerability class, and correspondingly rare."},
{t:"Container",a:"Docker",d:"Cloud & Infrastructure",def:"An application packaged with its dependencies, sharing the host kernel. Fast and portable, but isolation is weaker than a VM's."},
{t:"Container image",a:"",d:"Cloud & Infrastructure",def:"The read-only template a container starts from. Base images carry their own vulnerabilities, so scanning and rebuilding matter as much as your code."},
{t:"Container escape",a:"",d:"Cloud & Infrastructure",def:"Breaking out of a container to the host. Usually the result of privileged mode, a mounted socket, or an unpatched kernel."},
{t:"Kubernetes",a:"K8s",d:"Cloud & Infrastructure",def:"The dominant container orchestrator. Powerful, and insecure by default in ways that need deliberate configuration to fix."},
{t:"Pod",a:"",d:"Cloud & Infrastructure",def:"Kubernetes' smallest deployable unit — one or more containers sharing a network identity and storage."},
{t:"Service mesh",a:"Istio, Linkerd",d:"Cloud & Infrastructure",def:"A layer that handles service-to-service traffic, giving mutual TLS, policy, and telemetry without changing application code."},
{t:"Serverless",a:"FaaS, Lambda",d:"Cloud & Infrastructure",def:"Running functions without managing servers. No host to patch, but function permissions and event sources become the security surface."},
{t:"Infrastructure as code",a:"IaC — Terraform, CloudFormation",d:"Cloud & Infrastructure",def:"Defining infrastructure in version-controlled files. Makes environments reviewable and repeatable — and replicates a mistake everywhere instantly."},
{t:"Immutable infrastructure",a:"",d:"Cloud & Infrastructure",def:"Replacing servers instead of patching them in place. Removes configuration drift and quietly destroys most attacker persistence."},
{t:"Configuration drift",a:"",d:"Cloud & Infrastructure",def:"Live systems gradually diverging from their defined state through manual fixes. The reason a system that passed audit fails six months later."},
{t:"CSPM",a:"Cloud Security Posture Management",d:"Cloud & Infrastructure",def:"Continuously checking cloud configuration against policy — public buckets, open groups, missing encryption, over-broad roles."},
{t:"CWPP / CNAPP",a:"Cloud Workload / Native Application Protection Platform",d:"Cloud & Infrastructure",def:"Runtime protection for cloud workloads, and the bundled platforms that combine posture, workload, and identity checks."},
{t:"CIEM",a:"Cloud Infrastructure Entitlement Management",d:"Cloud & Infrastructure",def:"Finding and trimming excessive cloud permissions. Most cloud identities hold far more rights than they ever use."},
{t:"IAM policy",a:"",d:"Cloud & Infrastructure",def:"The rules defining which identity may perform which action on which cloud resource. Wildcards in these are the most common cloud misconfiguration."},
{t:"Instance metadata service",a:"IMDS",d:"Cloud & Infrastructure",def:"A local endpoint that hands running instances their cloud credentials. Reachable via SSRF unless the hardened version is enforced."},
{t:"Security group",a:"Network ACL",d:"Cloud & Infrastructure",def:"Cloud firewall rules attached to resources or subnets. An accidentally open management port here is a recurring breach origin."},
{t:"Object storage",a:"S3, Blob, GCS",d:"Cloud & Infrastructure",def:"Cloud file storage addressed by key rather than path. Publicly-readable buckets remain one of the most common data exposures."},
{t:"Bastion host",a:"Jump box",d:"Cloud & Infrastructure",def:"A single hardened, monitored entry point for administrative access to a private network, so nothing else needs exposing."},
{t:"Backup",a:"",d:"Cloud & Infrastructure",def:"A separate copy of data that can be restored. Untested backups are a plan, not a control — and ransomware crews delete the ones they can reach."},
{t:"3-2-1 rule",a:"",d:"Cloud & Infrastructure",def:"Three copies of data, on two media types, with one off-site. Modern versions add one offline or immutable copy."},
{t:"Immutable backup",a:"WORM",d:"Cloud & Infrastructure",def:"Backups that cannot be altered or deleted for a set period, even by an administrator. The specific answer to ransomware deleting backups."},
{t:"RTO / RPO",a:"Recovery Time / Point Objective",d:"Cloud & Infrastructure",def:"How fast you must be back, and how much data you can afford to lose. Two numbers that decide the entire backup architecture."},
{t:"Disaster recovery",a:"DR",d:"Cloud & Infrastructure",def:"Restoring technology after a major failure. Distinct from business continuity, which covers how the organisation keeps operating meanwhile."},
{t:"High availability",a:"HA",d:"Cloud & Infrastructure",def:"Design that survives component failure without downtime, through redundancy and failover. Availability is a security property too."},
{t:"CDN",a:"Content Delivery Network",d:"Cloud & Infrastructure",def:"Distributed edge servers caching content close to users. Also a practical place to absorb denial-of-service traffic and enforce WAF rules."},
{t:"WAF",a:"Web Application Firewall",d:"Cloud & Infrastructure",def:"Filters HTTP requests against attack patterns. Buys time before a patch; it does not fix the underlying flaw."},
{t:"Rate limiting",a:"",d:"Cloud & Infrastructure",def:"Capping how many requests a client can make in a window. The simplest defence against brute force, scraping, and abuse."},
{t:"API gateway",a:"",d:"Cloud & Infrastructure",def:"A single front door for APIs handling authentication, rate limits, routing, and logging, so services do not each reimplement them."},
{t:"Edge computing",a:"",d:"Cloud & Infrastructure",def:"Processing data near where it is produced rather than in a central cloud. Cuts latency and bandwidth; multiplies the number of devices to secure."},
{t:"Data residency",a:"Data sovereignty",d:"Cloud & Infrastructure",def:"Legal requirements about where data physically lives and which government can compel access to it. A cloud region choice with legal consequences."},
{t:"Egress cost / lock-in",a:"",d:"Cloud & Infrastructure",def:"Charges for moving data out of a cloud, and the dependence they create. A commercial concern that becomes a resilience concern."},
/* --- Endpoints & Systems --- */
{t:"Endpoint",a:"",d:"Endpoints & Systems",def:"Any device a person uses to reach the network — laptop, phone, tablet, server. Where most intrusions begin and where most detection now lives."},
{t:"Operating system",a:"OS",d:"Endpoints & Systems",def:"The software managing hardware, memory, and processes. Its permission model is the boundary attackers are usually trying to cross."},
{t:"Kernel",a:"",d:"Endpoints & Systems",def:"The core of the operating system, running with full hardware access. Code running here can hide from everything above it."},
{t:"User space vs kernel space",a:"",d:"Endpoints & Systems",def:"The separation between ordinary programs and privileged system code. Crossing from one to the other is the goal of local privilege escalation."},
{t:"Patch",a:"",d:"Endpoints & Systems",def:"A vendor fix for a bug or vulnerability. Applying them promptly prevents more breaches than any tool you can buy."},
{t:"Patch Tuesday",a:"",d:"Endpoints & Systems",def:"Microsoft's monthly release of security fixes, on the second Tuesday. Exploit development against those fixes typically follows within days."},
{t:"Hardening",a:"",d:"Endpoints & Systems",def:"Removing unnecessary services, accounts, and features and tightening what remains. Cheap, unglamorous, and highly effective."},
{t:"Baseline / benchmark",a:"CIS Benchmarks",d:"Endpoints & Systems",def:"A published, agreed secure configuration for a platform. Gives you something concrete to measure drift against."},
{t:"Golden image",a:"",d:"Endpoints & Systems",def:"A standard, pre-hardened system image every machine is built from, so security settings are the default rather than a follow-up task."},
{t:"Antivirus",a:"AV",d:"Endpoints & Systems",def:"Signature and heuristic detection of malicious files. Necessary, insufficient, and blind to fileless and living-off-the-land activity."},
{t:"EDR",a:"Endpoint Detection and Response",d:"Endpoints & Systems",def:"An agent recording process, file, and network behaviour on the endpoint, with the ability to alert, hunt, and isolate. The successor to antivirus."},
{t:"XDR",a:"Extended Detection and Response",d:"Endpoints & Systems",def:"Correlating endpoint telemetry with identity, email, and cloud signals in one place. Often just a vendor's bundle under a new name."},
{t:"MDM",a:"Mobile Device Management",d:"Endpoints & Systems",def:"Central enrolment and policy for phones and laptops — encryption, passcodes, app control, remote wipe."},
{t:"BYOD",a:"Bring Your Own Device",d:"Endpoints & Systems",def:"Staff using personal devices for work. Convenient, and it puts corporate data on hardware you do not control or get to inspect."},
{t:"Application allow-listing",a:"Whitelisting",d:"Endpoints & Systems",def:"Only approved executables may run. Extremely strong, operationally demanding, and impractical for developer machines."},
{t:"Full-disk encryption",a:"BitLocker, FileVault, LUKS",d:"Endpoints & Systems",def:"Encrypting the whole drive so a lost or stolen device gives up nothing. Protects data at rest, not a running unlocked machine."},
{t:"Secure Boot",a:"",d:"Endpoints & Systems",def:"Firmware refusing to load unsigned boot code, blocking bootkits before the operating system starts."},
{t:"UEFI / BIOS",a:"Firmware",d:"Endpoints & Systems",def:"The low-level code that starts the hardware. Rarely patched, hard to inspect, and highly persistent when compromised."},
{t:"Privilege separation",a:"",d:"Endpoints & Systems",def:"Running each component with only the rights it needs, so a compromise in one part does not hand over the whole system."},
{t:"Sudo / runas",a:"",d:"Endpoints & Systems",def:"Mechanisms for running a single command with elevated rights instead of working as an administrator all day. Also a valuable audit trail."},
{t:"Local admin rights",a:"",d:"Endpoints & Systems",def:"Full control of one machine. Removing standing local admin from ordinary users blocks a large share of malware outright."},
{t:"UAC",a:"User Account Control",d:"Endpoints & Systems",def:"Windows' prompt before elevated actions. A speed bump rather than a boundary — plenty of documented bypasses exist."},
{t:"Group Policy",a:"GPO",d:"Endpoints & Systems",def:"Windows' central mechanism for pushing configuration to domain machines. Also a superb attacker tool once domain admin is obtained."},
{t:"PowerShell",a:"",d:"Endpoints & Systems",def:"Windows' scripting and administration shell. Enormously useful to admins and attackers alike, which is why script block logging matters."},
{t:"SSH",a:"Secure Shell",d:"Endpoints & Systems",def:"Encrypted remote command-line access. Key-based authentication should replace passwords, and unmanaged authorised_keys entries are a persistence route."},
{t:"RDP",a:"Remote Desktop Protocol",d:"Endpoints & Systems",def:"Windows remote graphical access. Exposed to the internet, it is one of the most-attacked services in existence."},
{t:"Sysmon",a:"",d:"Endpoints & Systems",def:"A free Windows tool producing detailed process, network, and file telemetry. The cheapest meaningful upgrade to endpoint visibility."},
{t:"Event log",a:"",d:"Endpoints & Systems",def:"The operating system's record of what happened. Default retention is short, so shipping logs off-host is essential before an attacker clears them."},
{t:"Registry",a:"Windows Registry",d:"Endpoints & Systems",def:"Windows' central configuration database. A common place for malware to persist, since certain keys run automatically at boot or login."},
{t:"Scheduled task / cron",a:"",d:"Endpoints & Systems",def:"Built-in job schedulers. Legitimate everywhere, and among the first things to check for attacker persistence."},
{t:"Process injection",a:"",d:"Endpoints & Systems",def:"Running malicious code inside another, trusted process so it inherits that process's identity and looks normal."},
{t:"DLL hijacking",a:"",d:"Endpoints & Systems",def:"Placing a malicious library where a trusted program will load it first. Turns a legitimate signed application into the malware's launcher."},
{t:"Virtualisation",a:"",d:"Endpoints & Systems",def:"Running multiple isolated systems on one machine. The basis of cloud, and a safe place to detonate suspicious files."},
{t:"OT / ICS",a:"Operational Technology / Industrial Control Systems",d:"Endpoints & Systems",def:"Computers that run physical processes — plants, grids, pipelines. Long lifespans, no patch windows, and safety outranks confidentiality."},
{t:"SCADA",a:"Supervisory Control and Data Acquisition",d:"Endpoints & Systems",def:"The monitoring and control layer above industrial equipment. Historically built for isolated networks and now, unhelpfully, often reachable."},
{t:"IoT",a:"Internet of Things",d:"Endpoints & Systems",def:"Networked physical devices — cameras, sensors, meters. Weak defaults, rare updates, and long deployments make them ideal botnet recruits."},
{t:"Firmware update",a:"",d:"Endpoints & Systems",def:"Replacing the low-level software on a device. Often manual, sometimes unsigned, and the reason many devices stay vulnerable for years."},
{t:"End-of-life",a:"EOL / unsupported",d:"Endpoints & Systems",def:"Software the vendor no longer patches. Every future vulnerability in it stays open permanently, so EOL is a security deadline, not an IT one."},
/* --- Defense & Operations --- */
{t:"SOC",a:"Security Operations Centre",d:"Defense & Operations",def:"The team and tooling that monitor, triage, and respond to security events. In-house, outsourced, or a mix."},
{t:"SIEM",a:"Security Information and Event Management",d:"Defense & Operations",def:"Central log collection, correlation, and alerting. Only as good as the sources feeding it and the rules written on top."},
{t:"SOAR",a:"Security Orchestration, Automation and Response",d:"Defense & Operations",def:"Automating repetitive response steps through playbooks — enrich, contain, notify — so analysts handle the judgement calls."},
{t:"Detection engineering",a:"",d:"Defense & Operations",def:"Treating detections as code: written, tested, version-controlled, and measured. The shift from buying alerts to building them."},
{t:"Detection as code",a:"",d:"Defense & Operations",def:"Managing detection rules in a repository with review and CI, so changes are traceable and testable like any other software."},
{t:"Sigma",a:"",d:"Defense & Operations",def:"A vendor-neutral format for writing detection rules that can be converted to run on different SIEMs. The shared language for sharing detections."},
{t:"YARA",a:"",d:"Defense & Operations",def:"A pattern-matching language for identifying malware families by content. Widely used in threat hunting and malware triage."},
{t:"True / false positive",a:"",d:"Defense & Operations",def:"A real detection versus a false alarm. False positive volume, not detection coverage, is what usually breaks a SOC."},
{t:"Alert fatigue",a:"",d:"Defense & Operations",def:"Analysts becoming numb to alerts through sheer volume. The mechanism by which a genuine alert is closed unread."},
{t:"Triage",a:"",d:"Defense & Operations",def:"Rapidly deciding whether an alert is real and how urgent. The gatekeeping step between monitoring and incident response."},
{t:"Threat hunting",a:"",d:"Defense & Operations",def:"Proactively searching for intrusions that no alert fired on, driven by a hypothesis rather than a queue."},
{t:"Incident response",a:"IR",d:"Defense & Operations",def:"The structured process of handling a confirmed security incident. Usually framed as prepare, detect, contain, eradicate, recover, learn."},
{t:"Containment",a:"",d:"Defense & Operations",def:"Stopping an incident spreading — isolating hosts, disabling accounts, blocking traffic — before removing the attacker."},
{t:"Eradication",a:"",d:"Defense & Operations",def:"Removing the attacker's access completely: malware, backdoors, added accounts, altered configuration, rogue tokens."},
{t:"Recovery",a:"",d:"Defense & Operations",def:"Bringing systems back into service safely and confirming the environment is clean. Restoring too early reinfects everything."},
{t:"Post-incident review",a:"Lessons learned, blameless postmortem",d:"Defense & Operations",def:"Examining what happened and why, without hunting individuals. Blame guarantees the next incident is reported late or not at all."},
{t:"Playbook / runbook",a:"",d:"Defense & Operations",def:"Written steps for a specific scenario. Their real value is that they work at three in the morning when nobody is thinking clearly."},
{t:"Tabletop exercise",a:"",d:"Defense & Operations",def:"A discussion-based rehearsal of an incident scenario. Cheap, and reliably exposes decision-making and communication gaps."},
{t:"Chain of custody",a:"",d:"Defense & Operations",def:"Documented handling of evidence from collection onwards. Break it and the evidence may be worthless in a legal proceeding."},
{t:"Digital forensics",a:"DFIR",d:"Defense & Operations",def:"Recovering and analysing digital evidence to establish what happened. Paired with incident response as one discipline."},
{t:"Order of volatility",a:"",d:"Defense & Operations",def:"Collect the most perishable evidence first — memory, then network state, then disk. Pulling the plug destroys the most useful data."},
{t:"Memory forensics",a:"",d:"Defense & Operations",def:"Analysing RAM for injected code, decrypted secrets, and running processes that never touched disk. Often the only place fileless malware exists."},
{t:"Timeline analysis",a:"",d:"Defense & Operations",def:"Building an ordered sequence of events across sources to reconstruct an intrusion and find the initial access point."},
{t:"Log retention",a:"",d:"Defense & Operations",def:"How long logs are kept. Intrusions are often found months later, so short retention quietly makes investigation impossible."},
{t:"Telemetry",a:"",d:"Defense & Operations",def:"The raw signals systems emit. Detection is limited by telemetry — you cannot alert on something nobody records."},
{t:"Baseline / anomaly detection",a:"",d:"Defense & Operations",def:"Learning what normal looks like and alerting on deviation. Catches novel attacks and generates plenty of noise doing it."},
{t:"UEBA",a:"User and Entity Behaviour Analytics",d:"Defense & Operations",def:"Behavioural profiling of users and machines to spot compromised accounts and insiders acting out of character."},
{t:"Deception technology",a:"Honeypot, canary token",d:"Defense & Operations",def:"Fake systems, files, or credentials that nothing legitimate should ever touch. Very low false-positive rate when they trigger."},
{t:"Vulnerability management",a:"",d:"Defense & Operations",def:"Finding, prioritising, fixing, and verifying vulnerabilities as a continuous cycle. Prioritisation is the hard part, not scanning."},
{t:"Vulnerability scanner",a:"",d:"Defense & Operations",def:"A tool that checks systems against a database of known flaws. Reports what might be vulnerable, not what is exploitable in your context."},
{t:"Attack surface management",a:"ASM / EASM",d:"Defense & Operations",def:"Continuously discovering what of yours is exposed to the internet, including assets nobody remembered owning."},
{t:"Purple teaming",a:"",d:"Defense & Operations",def:"Red and blue working together, running known techniques to check whether detection actually fires. Improvement rather than scorekeeping."},
{t:"Breach and attack simulation",a:"BAS",d:"Defense & Operations",def:"Automated, continuous safe replay of attack techniques to validate that controls and detections still work after changes."},
{t:"MTTD / MTTR",a:"Mean Time to Detect / Respond",d:"Defense & Operations",def:"How long detection and response take on average. The two operational metrics that most reflect real-world damage."},
{t:"Runbook automation",a:"",d:"Defense & Operations",def:"Turning repeated manual response steps into scripts or workflows. Consistency under pressure, and a free audit trail."},
{t:"On-call / escalation",a:"",d:"Defense & Operations",def:"Defined rotas and paths for raising an incident out of hours. An unclear escalation path costs more time than any tool saves."},
{t:"Crisis communications",a:"",d:"Defense & Operations",def:"Deciding in advance who says what to staff, customers, regulators, and press. Prepared badly, it turns an incident into a reputational event."},
{t:"Business continuity",a:"BCP",d:"Defense & Operations",def:"How the organisation keeps operating during disruption, including manual fallbacks. Broader than technical disaster recovery."},
/* --- Governance, Risk & Compliance --- */
{t:"CIA triad",a:"Confidentiality, Integrity, Availability",d:"Governance, Risk & Compliance",def:"The three properties security exists to protect. Most controls trade one against another, and naming which one you are protecting sharpens the argument."},
{t:"Non-repudiation",a:"",d:"Governance, Risk & Compliance",def:"Being able to prove someone took an action so they cannot credibly deny it. What signatures and tamper-evident logs provide."},
{t:"Defence in depth",a:"",d:"Governance, Risk & Compliance",def:"Layering independent controls so no single failure is fatal. Assumes each layer will eventually fail, because it will."},
{t:"Risk appetite / tolerance",a:"",d:"Governance, Risk & Compliance",def:"How much risk leadership is willing to accept. Without it stated, every risk decision becomes an argument."},
{t:"Risk register",a:"",d:"Governance, Risk & Compliance",def:"The recorded list of known risks with owners, ratings, and treatment. Useful when actively reviewed, decorative when not."},
{t:"Risk treatment",a:"Accept, mitigate, transfer, avoid",d:"Governance, Risk & Compliance",def:"The four things you can do about a risk. Accepting is legitimate — provided someone with authority signs it."},
{t:"Inherent vs residual risk",a:"",d:"Governance, Risk & Compliance",def:"Risk before controls versus what remains after them. Residual risk is the number leadership should actually be shown."},
{t:"Control",a:"",d:"Governance, Risk & Compliance",def:"A safeguard reducing risk. Categorised as preventive, detective, or corrective, and as technical, administrative, or physical."},
{t:"Compensating control",a:"",d:"Governance, Risk & Compliance",def:"An alternative measure when the required control is not feasible. Must genuinely meet the intent, not merely be documented as if it does."},
{t:"Policy / standard / procedure",a:"",d:"Governance, Risk & Compliance",def:"Policy states intent, standards set specific requirements, procedures give the steps. Collapsing them into one document is why nobody follows any of them."},
{t:"ISO/IEC 27001",a:"",d:"Governance, Risk & Compliance",def:"The international standard for an information security management system, and certifiable. It assesses the management system, not the technical strength."},
{t:"NIST CSF",a:"NIST Cybersecurity Framework",d:"Governance, Risk & Compliance",def:"A voluntary framework organised around Govern, Identify, Protect, Detect, Respond, Recover. Widely used as a common structure for maturity conversations."},
{t:"NIST SP 800-53 / 800-171",a:"",d:"Governance, Risk & Compliance",def:"Detailed US federal control catalogues — 800-53 for federal systems, 800-171 for contractors handling controlled unclassified information."},
{t:"SOC 2",a:"",d:"Governance, Risk & Compliance",def:"An audit report on a service provider's controls against trust criteria. Type I is a point in time; Type II covers a period and is the one to ask for."},
{t:"PCI DSS",a:"Payment Card Industry Data Security Standard",d:"Governance, Risk & Compliance",def:"Mandatory rules for anyone handling payment card data. Contractual rather than statutory, and enforced by fines and lost processing rights."},
{t:"GDPR",a:"General Data Protection Regulation",d:"Governance, Risk & Compliance",def:"The EU regulation governing personal data. Extraterritorial, principles-based, and backed by fines up to four percent of global turnover."},
{t:"Personal data / PII",a:"Personally Identifiable Information",d:"Governance, Risk & Compliance",def:"Data relating to an identifiable person. GDPR's definition is deliberately broad and includes IP addresses and device identifiers."},
{t:"Special category data",a:"Sensitive personal data",d:"Governance, Risk & Compliance",def:"Health, biometrics, ethnicity, religion, sexuality, politics, union membership. Higher legal protection and higher real-world harm if exposed."},
{t:"Lawful basis",a:"",d:"Governance, Risk & Compliance",def:"The legal justification for processing personal data — consent, contract, legal obligation, vital interests, public task, legitimate interests."},
{t:"Data minimisation",a:"",d:"Governance, Risk & Compliance",def:"Collect only what you need and keep it only as long as you need it. The control that shrinks breach impact more than any tool."},
{t:"Purpose limitation",a:"",d:"Governance, Risk & Compliance",def:"Data collected for one stated purpose may not be quietly reused for another. The principle most often broken by analytics and AI training."},
{t:"Data subject rights",a:"DSAR",d:"Governance, Risk & Compliance",def:"Individuals' rights to access, correct, delete, or port their data, with statutory response deadlines."},
{t:"DPIA",a:"Data Protection Impact Assessment",d:"Governance, Risk & Compliance",def:"A required assessment before high-risk processing, documenting risks to people and how they are mitigated. Best done at design, not sign-off."},
{t:"Privacy by design",a:"",d:"Governance, Risk & Compliance",def:"Building privacy protections into a system from the start, with privacy-protective defaults. A GDPR obligation, not a philosophy."},
{t:"Anonymisation vs pseudonymisation",a:"",d:"Governance, Risk & Compliance",def:"Anonymised data cannot be linked back and leaves scope; pseudonymised data can be re-linked with a key and is still personal data."},
{t:"Re-identification",a:"",d:"Governance, Risk & Compliance",def:"Reconnecting supposedly anonymous records to people, usually by combining datasets. The reason true anonymisation is much harder than it sounds."},
{t:"Differential privacy",a:"",d:"Governance, Risk & Compliance",def:"Adding calibrated statistical noise so aggregate results are useful while no individual's presence can be inferred."},
{t:"Breach notification",a:"",d:"Governance, Risk & Compliance",def:"The legal duty to report certain breaches within a deadline — 72 hours to a regulator under GDPR, and to affected people if the risk is high."},
{t:"Data classification",a:"",d:"Governance, Risk & Compliance",def:"Labelling data by sensitivity so handling rules can follow the label. Three or four tiers work; ten do not."},
{t:"DLP",a:"Data Loss Prevention",d:"Governance, Risk & Compliance",def:"Tooling that spots and blocks sensitive data leaving. Good at accidents, weak against a determined insider."},
{t:"Retention schedule",a:"",d:"Governance, Risk & Compliance",def:"How long each category of data is kept before deletion. Data you deleted on schedule cannot be breached or subpoenaed."},
{t:"Third-party risk",a:"TPRM / vendor risk",d:"Governance, Risk & Compliance",def:"Managing the risk suppliers introduce. You can outsource the processing, but not the accountability."},
{t:"Due diligence",a:"",d:"Governance, Risk & Compliance",def:"Assessing a supplier's security before signing. Questionnaires are the norm; evidence and audit rights are what actually matter."},
{t:"SBOM",a:"Software Bill of Materials",d:"Governance, Risk & Compliance",def:"A machine-readable inventory of components in a piece of software. Turns a new vulnerability disclosure into a lookup rather than a scramble."},
{t:"CVE / CVSS",a:"Common Vulnerabilities and Exposures / Scoring System",d:"Governance, Risk & Compliance",def:"CVE is the unique identifier for a known flaw; CVSS scores its severity out of ten. CVSS ignores your context, so it is an input, not a decision."},
{t:"KEV",a:"Known Exploited Vulnerabilities catalogue",d:"Governance, Risk & Compliance",def:"CISA's list of vulnerabilities confirmed exploited in the wild. A far better patching priority than CVSS score alone."},
{t:"EPSS",a:"Exploit Prediction Scoring System",d:"Governance, Risk & Compliance",def:"A probability that a vulnerability will be exploited in the next 30 days. Pairs well with CVSS to cut patch backlogs to something achievable."},
{t:"Audit trail",a:"",d:"Governance, Risk & Compliance",def:"A tamper-evident record of who did what and when. Required by most frameworks and indispensable during an investigation."},
{t:"Segregation of duties",a:"SoD",d:"Governance, Risk & Compliance",def:"Splitting a sensitive process so no one person can complete it alone. The standard control against both fraud and single-point mistakes."},
{t:"Security awareness training",a:"",d:"Governance, Risk & Compliance",def:"Teaching staff to recognise and report attacks. Effective when it is short, frequent, and safe to report to; useless as an annual slideshow."},
/* --- AI & Emerging Tech --- */
{t:"Machine learning",a:"ML",d:"AI & Emerging Tech",def:"Systems that derive rules from data rather than being programmed with them. The behaviour reflects the training data, including its errors and bias."},
{t:"Large language model",a:"LLM",d:"AI & Emerging Tech",def:"A model trained on vast text to predict likely continuations. Fluent by construction, and fluency is not the same as being correct."},
{t:"Training data",a:"",d:"AI & Emerging Tech",def:"The corpus a model learns from. Its provenance, licensing, and bias become properties of the finished system."},
{t:"Inference",a:"",d:"AI & Emerging Tech",def:"Running a trained model to get an output. Where cost, latency, and most data-exposure questions actually live."},
{t:"Prompt",a:"",d:"AI & Emerging Tech",def:"The instruction and context given to a model. In most current systems it is also, unhelpfully, the security boundary."},
{t:"System prompt",a:"",d:"AI & Emerging Tech",def:"Standing instructions set by the developer ahead of user input. Treat it as configuration, never as a secret — it leaks."},
{t:"Context window",a:"",d:"AI & Emerging Tech",def:"How much text a model can consider at once. Anything beyond it is dropped or summarised, which quietly changes behaviour."},
{t:"Token",a:"",d:"AI & Emerging Tech",def:"The chunk of text a model processes, roughly a word fragment. The unit of both pricing and context limits."},
{t:"Hallucination",a:"Confabulation",d:"AI & Emerging Tech",def:"A confident, fluent, wrong output. Not a bug to be patched out but a property of prediction, which is why verification has to be designed in."},
{t:"Prompt injection",a:"",d:"AI & Emerging Tech",def:"Hostile instructions hidden in content a model reads, hijacking its behaviour. The defining security problem of LLM applications."},
{t:"Indirect prompt injection",a:"",d:"AI & Emerging Tech",def:"Injection delivered through a document, web page, or email the model retrieves, so the attacker never talks to the system directly."},
{t:"Jailbreak",a:"",d:"AI & Emerging Tech",def:"Framing that persuades a model past its safety training. Distinct from prompt injection, which targets the application's instructions."},
{t:"Data poisoning",a:"",d:"AI & Emerging Tech",def:"Corrupting training or retrieval data so the model learns something the attacker chose. Very hard to detect after the fact."},
{t:"Model inversion / membership inference",a:"",d:"AI & Emerging Tech",def:"Extracting training data, or proving a specific record was in the training set, by probing the model. A privacy problem for models trained on personal data."},
{t:"Model extraction",a:"Model stealing",d:"AI & Emerging Tech",def:"Reconstructing a proprietary model by querying it enough times to train a copy of its behaviour."},
{t:"Adversarial example",a:"",d:"AI & Emerging Tech",def:"Input perturbed slightly so a model misclassifies it while a person sees nothing unusual. The classic attack on vision systems."},
{t:"RAG",a:"Retrieval-Augmented Generation",d:"AI & Emerging Tech",def:"Fetching relevant documents and giving them to a model as context. It grounds answers — and makes every retrievable document an injection surface."},
{t:"Vector database",a:"Embedding store",d:"AI & Emerging Tech",def:"Storage for numeric representations of text so similar meaning can be found by proximity. The retrieval half of RAG, and it inherits the source's access rules only if you make it."},
{t:"Embedding",a:"",d:"AI & Emerging Tech",def:"A numeric representation capturing meaning, so similar things sit close together. Not anonymised — original text can often be approximately recovered."},
{t:"Fine-tuning",a:"",d:"AI & Emerging Tech",def:"Further training a base model on specific data to specialise it. Anything in that data is baked into the weights and cannot be selectively deleted."},
{t:"Guardrails",a:"",d:"AI & Emerging Tech",def:"Filters and policies around a model's inputs and outputs. Necessary, probabilistic, and not a substitute for real authorisation checks."},
{t:"Human in the loop",a:"HITL",d:"AI & Emerging Tech",def:"Requiring a person to approve consequential AI-driven actions. Only meaningful if the reviewer has the time and information to genuinely disagree."},
{t:"Agentic AI",a:"AI agent",d:"AI & Emerging Tech",def:"A model given tools and the autonomy to take multi-step actions. It converts a text-generation risk into a systems-and-permissions risk."},
{t:"Tool use / function calling",a:"",d:"AI & Emerging Tech",def:"Letting a model invoke external functions or APIs. Whatever the tool can do, a successful prompt injection can do."},
{t:"MCP",a:"Model Context Protocol",d:"AI & Emerging Tech",def:"An open standard for connecting models to tools and data sources. Each connected server is a new trust relationship to review."},
{t:"Model card",a:"",d:"AI & Emerging Tech",def:"Documentation of a model's intended use, training data, evaluation, and limitations. The AI equivalent of a datasheet."},
{t:"AI red teaming",a:"",d:"AI & Emerging Tech",def:"Deliberately probing a model or AI system for harmful, biased, or unsafe behaviour before users find it."},
{t:"Explainability",a:"XAI",d:"AI & Emerging Tech",def:"Being able to say why a model produced a given output. Increasingly a legal requirement for decisions affecting people."},
{t:"Algorithmic bias",a:"",d:"AI & Emerging Tech",def:"Systematic unfairness in outputs, usually inherited from data or objectives. A safety and legal problem, not only an accuracy one."},
{t:"EU AI Act",a:"",d:"AI & Emerging Tech",def:"The EU's risk-tiered regulation of AI systems, with outright bans at the top and obligations scaling with risk. Extraterritorial, like GDPR."},
{t:"Deepfake",a:"Synthetic media",d:"AI & Emerging Tech",def:"AI-generated audio, image, or video imitating a real person. Already routine in payment fraud and executive impersonation."},
{t:"Content provenance",a:"C2PA",d:"AI & Emerging Tech",def:"Cryptographically signed metadata recording how a piece of media was made and edited. An attempt to make authenticity checkable rather than assumed."},
{t:"Watermarking",a:"",d:"AI & Emerging Tech",def:"Embedding a detectable signal in AI-generated output. Helpful at scale, and generally removable by anyone who wants to remove it."},
{t:"Shadow AI",a:"",d:"AI & Emerging Tech",def:"Staff using AI tools without approval, often pasting confidential data into them. The current form of shadow IT, moving faster."},
{t:"Blockchain",a:"Distributed ledger",d:"AI & Emerging Tech",def:"An append-only ledger replicated across many parties. Strong integrity guarantees; no confidentiality, and no help if the data entered was wrong."},
{t:"Smart contract",a:"",d:"AI & Emerging Tech",def:"Code executing automatically on a blockchain. Immutable once deployed, which means bugs are permanent and expensive."},
{t:"Quantum computing",a:"",d:"AI & Emerging Tech",def:"Computation using quantum states, able in principle to break RSA and elliptic-curve cryptography. The reason post-quantum migration is starting now."},
{t:"Confidential computing",a:"TEE / enclave",d:"AI & Emerging Tech",def:"Processing data inside a hardware-protected enclave so even the host operating system cannot read it. Closes the in-use gap left by encryption at rest and in transit."},
/* --- Dev & Delivery --- */
{t:"Repository",a:"Repo",d:"Dev & Delivery",def:"The project folder plus its entire history of changes. Everything else in version control is an operation on a repository."},
{t:"Version control",a:"Git, VCS",d:"Dev & Delivery",def:"A system that records every change to a codebase, who made it and why, and lets you go back. Git is the near-universal one; GitHub and GitLab are hosts for it."},
{t:"Clone",a:"",d:"Dev & Delivery",def:"Copying a remote repository, including its full history, onto your own machine. The first command of most working days."},
{t:"Fork",a:"",d:"Dev & Delivery",def:"Your own server-side copy of someone else's repository, so you can change it without write access to the original and propose the change back."},
{t:"Branch",a:"",d:"Dev & Delivery",def:"A named line of work running alongside the main one. It lets you build or break something without affecting what everyone else is using."},
{t:"main / master",a:"Default branch",d:"Dev & Delivery",def:"The branch treated as the source of truth. Most projects protect it so nothing lands without review."},
{t:"Commit",a:"",d:"Dev & Delivery",def:"A saved, described snapshot of your changes, recorded permanently in the history. The unit of work everything else — review, revert, blame — operates on."},
{t:"Commit message",a:"",d:"Dev & Delivery",def:"The note explaining what changed and why. The why is the part future-you cannot reconstruct from the diff."},
{t:"Staging area",a:"Index",d:"Dev & Delivery",def:"Git's holding pen between your working files and a commit. `git add` puts changes there so you can commit some edits and not others."},
{t:"Push",a:"",d:"Dev & Delivery",def:"Sending your local commits up to the remote repository so others — and any deployment pipeline — can see them. Nothing you have not pushed exists to anyone else."},
{t:"Pull",a:"",d:"Dev & Delivery",def:"Fetching changes from the remote and merging them into your branch. Pull before you start work, or you will be resolving conflicts later."},
{t:"Fetch",a:"",d:"Dev & Delivery",def:"Downloading remote changes without applying them to your working copy. The cautious half of a pull, when you want to look before you merge."},
{t:"Sync",a:"",d:"Dev & Delivery",def:"Bringing two copies into agreement — usually a pull followed by a push, so local and remote match. In GUIs it is often one button doing both."},
{t:"Remote",a:"origin, upstream",d:"Dev & Delivery",def:"A named repository your local copy talks to. `origin` is normally your own copy; `upstream` is the original you forked from."},
{t:"Merge",a:"",d:"Dev & Delivery",def:"Combining one branch's changes into another. Git does it automatically unless both sides edited the same lines."},
{t:"Merge conflict",a:"",d:"Dev & Delivery",def:"Two branches changed the same lines and Git refuses to guess. You pick what the file should say, then commit the resolution."},
{t:"Rebase",a:"",d:"Dev & Delivery",def:"Replaying your commits on top of an updated branch to give a straight history instead of a merge. Never rebase a branch other people have already pulled."},
{t:"Pull request",a:"PR / merge request / MR",d:"Dev & Delivery",def:"A proposal to merge one branch into another, with a place to discuss and review it first. Where code review, CI checks and approvals happen."},
{t:"Code review",a:"",d:"Dev & Delivery",def:"Another engineer reading a change before it lands. The cheapest place to catch both bugs and security mistakes."},
{t:"Diff",a:"",d:"Dev & Delivery",def:"The line-by-line difference between two versions — what was added, removed and changed. What you actually review, rather than the whole file."},
{t:"HEAD",a:"",d:"Dev & Delivery",def:"A pointer to the commit you currently have checked out. `HEAD~1` is the one before it."},
{t:"Tag",a:"",d:"Dev & Delivery",def:"A permanent name pinned to a specific commit, normally a release like v2.1.0. Unlike a branch, it does not move."},
{t:"Release",a:"",d:"Dev & Delivery",def:"A tagged, packaged version handed to users, usually with notes and built artifacts attached."},
{t:"Revert",a:"",d:"Dev & Delivery",def:"Creating a new commit that undoes an earlier one, leaving the history intact. The safe way to back out a change that is already public."},
{t:"Reset",a:"",d:"Dev & Delivery",def:"Moving your branch pointer backwards, optionally throwing away work. Powerful locally, destructive if you force-push the result."},
{t:"Cherry-pick",a:"",d:"Dev & Delivery",def:"Copying one specific commit onto another branch. How an urgent fix reaches a release branch without dragging everything else with it."},
{t:"Stash",a:"",d:"Dev & Delivery",def:"Parking uncommitted changes temporarily so you can switch context, then bringing them back."},
{t:".gitignore",a:"",d:"Dev & Delivery",def:"A list of paths Git should never track — build output, local config, secrets. The first line of defence against committing a key by accident."},
{t:"Monorepo",a:"",d:"Dev & Delivery",def:"Many projects in one repository, sharing tooling and history. Simpler coordination, heavier tooling; the alternative is many small repos."},
{t:"CI",a:"Continuous Integration",d:"Dev & Delivery",def:"Automatically building and testing every change as it is pushed, so problems surface in minutes rather than at release."},
{t:"CD",a:"Continuous Delivery / Deployment",d:"Dev & Delivery",def:"Delivery keeps every change releasable at a button press; deployment ships it automatically once checks pass. The two are often written as one and mean different things."},
{t:"Pipeline",a:"Workflow, GitHub Actions",d:"Dev & Delivery",def:"The scripted sequence that runs on a push — install, lint, test, build, scan, deploy. It holds real credentials, which makes it a genuine attack surface."},
{t:"Build",a:"",d:"Dev & Delivery",def:"Turning source code into something runnable — compiled, bundled, containerised. A build that only works on one machine is a bug."},
{t:"Artifact",a:"",d:"Dev & Delivery",def:"The output of a build: a binary, a container image, a zipped bundle. What actually gets deployed, as opposed to the source."},
{t:"Deploy",a:"Ship, release to production",d:"Dev & Delivery",def:"Putting a built version onto the servers where real users reach it. Small, frequent deploys are safer than big rare ones, because there is less to unpick when one goes wrong."},
{t:"Environment",a:"dev / staging / production",d:"Dev & Delivery",def:"Separate copies of the system for building, testing and real use. Staging should resemble production closely enough that passing there means something."},
{t:"Production",a:"Prod",d:"Dev & Delivery",def:"The live system real people depend on. Every rule about review, backups and change control exists because of what happens here."},
{t:"Rollback",a:"",d:"Dev & Delivery",def:"Returning to the previous working version after a bad deploy. Knowing you can roll back in one step is what makes frequent deploys reasonable."},
{t:"Blue-green / canary deploy",a:"",d:"Dev & Delivery",def:"Two ways to release safely: run two full environments and switch traffic, or send the new version to a small slice of users first and watch."},
{t:"Feature flag",a:"Toggle",d:"Dev & Delivery",def:"A switch that turns functionality on or off without a deploy. Separates releasing code from releasing the feature — and stale flags become their own mess."},
{t:"Hotfix",a:"",d:"Dev & Delivery",def:"An urgent fix taken straight to production outside the normal cycle. Legitimate, and worth logging, because it skipped the usual checks."},
{t:"Semantic versioning",a:"SemVer",d:"Dev & Delivery",def:"MAJOR.MINOR.PATCH, where major means a breaking change, minor adds features, patch fixes bugs. It tells you how nervous to be about upgrading."},
{t:"Breaking change",a:"",d:"Dev & Delivery",def:"A change that stops existing users' code or configuration working. It needs a major version bump and a note, not a quiet release."},
{t:"Dependency",a:"Package, library",d:"Dev & Delivery",def:"Third-party code your project relies on. Most of a modern application is dependencies, which is why supply chain security is a real concern."},
{t:"Package manager",a:"npm, pip, cargo, apt",d:"Dev & Delivery",def:"The tool that installs and updates dependencies. Also the channel a typosquatted or hijacked package arrives through."},
{t:"Lockfile",a:"package-lock.json, requirements.txt",d:"Dev & Delivery",def:"A record of the exact dependency versions installed, so every machine and every build gets the same ones. Commit it."},
{t:"Environment variable",a:"env var, .env",d:"Dev & Delivery",def:"Configuration passed to a program at runtime instead of written into the code. Where secrets belong in development — and `.env` belongs in `.gitignore`."},
{t:"Linter / formatter",a:"",d:"Dev & Delivery",def:"Tools that flag likely mistakes and enforce consistent style automatically. They end style arguments and catch a surprising number of bugs."},
{t:"Unit / integration test",a:"",d:"Dev & Delivery",def:"Unit tests check one piece in isolation; integration tests check the pieces working together. You need both, and integration tests are the ones people skip."},
{t:"Regression",a:"",d:"Dev & Delivery",def:"Something that used to work and now does not. Regression tests exist so the same bug cannot come back twice unnoticed."},
{t:"Refactor",a:"",d:"Dev & Delivery",def:"Restructuring code without changing what it does. If behaviour changed, it was not a refactor, and it needs reviewing as a real change."},
{t:"Technical debt",a:"",d:"Dev & Delivery",def:"Shortcuts taken to ship faster that cost more later. Sometimes a good trade — but only if someone writes down that it was taken."},
{t:"API",a:"Application Programming Interface",d:"Dev & Delivery",def:"The defined way one piece of software talks to another. Everything in the library section of this site is reached through one."},
{t:"REST / GraphQL",a:"",d:"Dev & Delivery",def:"Two API styles: REST exposes resources at URLs and you take what each returns; GraphQL exposes one endpoint and you ask for exactly the fields you want."},
{t:"API endpoint",a:"Route",d:"Dev & Delivery",def:"A specific URL an API exposes for one operation. Each one needs its own authorisation check — this is where broken access control usually lives."},
{t:"Webhook",a:"",d:"Dev & Delivery",def:"A URL you register so another service can push events to you as they happen, instead of you polling. Verify the signature, or anyone can post to it."},
{t:"SDK / CLI",a:"Software Development Kit / Command Line Interface",d:"Dev & Delivery",def:"A library that wraps an API in your language, and a terminal tool that wraps it for humans and scripts. Usually easier and safer than hand-rolling HTTP calls."},
{t:"JSON / YAML",a:"",d:"Dev & Delivery",def:"The two everyday data formats: JSON for APIs, YAML for configuration. YAML's indentation and loose typing cause more outages than they should."},
{t:"Rate limit",a:"Quota",d:"Dev & Delivery",def:"How many API calls you are allowed in a window. Read it before writing the loop, cache the responses, and handle the 429 rather than retrying blindly."},
{t:"Idempotent",a:"",d:"Dev & Delivery",def:"An operation that gives the same result whether you run it once or five times. What makes safe retries possible."},
{t:"Observability",a:"Logs, metrics, traces",d:"Dev & Delivery",def:"Being able to tell what a running system is doing from the outside. Logs say what happened, metrics count it, traces follow one request across services."},
{t:"SLA / SLO",a:"Service Level Agreement / Objective",d:"Dev & Delivery",def:"The availability you promise contractually, and the internal target you actually manage to. The objective should be stricter than the agreement."},
{t:"Upstream / downstream",a:"",d:"Dev & Delivery",def:"Upstream is the project or service you depend on; downstream is whoever depends on you. Vulnerabilities travel downstream, fixes come from upstream."},
{t:"Deprecation",a:"EOL notice",d:"Dev & Delivery",def:"Formal warning that something will be removed, with a date. The window in which to migrate calmly rather than in an incident."},
{t:"Documentation",a:"README, docs",d:"Dev & Delivery",def:"The instructions that let someone else run, use or fix the thing. A project without a README is a project only its author can operate."}
];
